"Set an item's attribute" on peut maintenant créer un attribut à un ite…
Hypertopic/Porphyry pull request #103
Opened 2018-06-08 10:46 UTC by Pinksea

…m, ici le fichier config.js pointe vers l'environnement de test

## Content

Please describe your contribution here...

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2018-06-12 09:30 UTC, benel requested changes

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +const hypertopic = require('hypertopic');
> Each committed line is (...) useful (it would not work if removed)

Cette constante n'est pas utilisée (elle est même surchargée par une variable de même nom !).

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +
> Each committed line is (...) useful (it would not work if removed)

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +     isClick: false,
> Each committed line is (...) in English

C'est effectivement une bonne pratique de nommer les booléens sous la forme `is***`. Par contre : 

- ça devrait être `isClicked` pour être correct grammaticalement,
- le fait que ce soit cliqué ou pas est très proche de l'interface et du coup très loin du "métier".

À quoi sert ce "clic" ? Si par exemple c'est pour le mode édition, la propriété  pourrait s'appeler : `isEditable`.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +   this.buttonCreer = this.buttonCreer.bind(this);
> Each committed line is (...) in English

Je doute que `créer` et `valider` se disent comme ça en anglais.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +
> Each committed line is (...) useful (it would not work if removed)

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +              {this.state.isClick ? this.buttonValider():""}
Pourquoi ne pas fusionner les deux expressions ternaires en une seule ? 

```js
{this.state.isClick? this.buttonValider() : this.buttonCreer()}
```

C'est d'ailleurs pour cette raison qu'elles sont ternaires...

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +//Show button with the value valider
> if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message

Je ne suis pas convaincu par la nécessité de ce commentaire. Par contre, pensez à sauter une ligne entre les fonctions.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +  }
Les deux fonctions sont quasiment identiques.

Il serait beaucoup plus "esthétique" (et court) de mettre le code du bouton directement dans le constructeur et de mettre juste un contenu dynamique pour le nom du bouton.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> + return(
> Each committed line is (...) correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +//create a new attribute
> if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message

Je ne suis pas convaincu par la nécessité de ce commentaire. Par contre, pensez à sauter une ligne entre les fonctions.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +    if(key!="" && value!=""){
`if` n'est pas une fonction: il y a un espace avant la parenthèse.
Par ailleurs, il y a toujours un espace avant les accolades ouvrantes.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +     myObj[key] = value;
Pourquoi ces deux lignes et non directement, ligne 80 : 
```js
          .then(x => Object.assign(x, {[key]: value}))

```

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +    else console.log("Créez un attribut non vide");
Vous savez : peu d'usagers consultent la console ;)

Pensez à prévenir @Heliacerbonne de la nécessité de cette notification pour qu'elle puisse la prévoir dans la nouvelle interface.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +  // }
> Each committed line is (...) useful (it would not work if removed)

See https://en.wikipedia.org/wiki/Cruft

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +//check the value of isClick and when isClisk is click twice it call setAttribute to create a new attribute
> if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message

Si vous avez besoin de ce long commentaire (pas très clair d'ailleurs et contenant une coquille), c'est probablement que votre nom de fonction devrait être changé.

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +          }))
Si le `setState` est strictement le même dans les deux branches de la condition, c'est qu'il n'a rien à faire dans la condition...

2018-06-12 09:30 UTC, benel commented on src/components/Item/Item.jsx
> +    var value=document.getElementById("value").value; //retrieve the value of the input whiche is contains the value of the future attribute
> if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message

Vous pensez que ces deux lignes sont d'une complexité telle qu'elles nécessitent une longue explication ?

2018-06-13 13:04 UTC, Pinksea commented
Bonjour,  @benel 
J'ai modifié sur le code toutes les remarques que vous m'avez fait, dois-je faire un nouveau commit + un nouveau pull request ?
cordialement

2018-06-13 13:12 UTC, benel commented
> J'ai modifié sur le code toutes les remarques que vous m'avez fait

Bien. 

> dois-je faire un nouveau commit + un nouveau pull request ?

Vous pouvez amender (`amend`) votre commit. Profitez en pour : 

- bien appliquer les règles de formulation du titre,
- si vous avez des co-auteurs, les indiquer en co-auteurs (suivre le lien que je donne dans ma check-list).

Si vous voulez garder cette pull request et la mettre à jour, vous devrez forcer votre push (`-f`).

2018-06-14 16:14 UTC, benel commented
Pull request accepted (after a few edits). Code integrated into branch v7 (fb27c97bd977d53b3ea874f2e5212cf18a2c90ba). Well done!

2018-06-14 16:14 UTC, closed without merging