FEATURE & TEST: Add Facebook comment function in tiem (see #47)
Hypertopic/Porphyry pull request #110
Opened 2018-06-15 09:14 UTC by xuzhengyi1995

## Content

Add Facebook comment function in item  (see #47)

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2018-06-15 09:28 UTC, xuzhengyi1995 commented
I have changed all the cookies in environment values, but because it's a pull request, Travis-CI said that Encrypted environment variables have been removed for security reasons.

2018-06-19 14:25 UTC, benel requested changes
To provide the feature to the other teams faster, you should make a first PR with only the feature (with the required customization and doc).
The PR with tests can be requested once the feature is integrated.

2018-06-19 14:25 UTC, benel commented on src/components/Item/Item.jsx
> +      <FacebookProvider appId='566160170436215'>
It is important that each portfolio can be moderated by a different team. Therefore, the application ID of each portfolio should be customizable in Porphyry settings (for each portfolio). By default (when no application ID is set), the plugin should be disabled.

Because you add such a setting, you should document in the README how to get an application ID from Facebook and how to set a given portfolio to use it.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +Capybara.current_session.driver.browser.manage.add_cookie(name:"datr",value: ENV['FACEBOOK_COOKIES_datr'])
You should document in the README how to: 
- get the right values (from FB?),
- set up Travis.ci.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +  find("img[alt='"+item+"']").click
In order to click an image according to its `alt`, a simple `click_on` should work.

Moreover, this clause is already defined.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +    find(".notranslate._5rpu").native.send_keys(comment);
Seriously? Are there any other way to identify elements (more readable and more persistent way)?

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +Quand("un visiteur clique le {string} button") do |button|
Steps should not correspond to UI actions but to domain-related actions.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +Quand("un visiteur clique le {string} button") do |button|
Steps should be written in French.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +Alors ("on peut voir le comment {string}") do |comment|
Steps should be written in French.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +Soit ("un visiteur flotter sur la première comment") do
Steps should be written in French.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +    first_comment = first("._3-8y._5nz1.clearfix")
See previous comments on element address persistence.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +Quand ("un visiteur clique le Delete comment button et valide") do
Steps should be written in French.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +Alors ("la première comment a été supprimé") do
Steps should be written in French.

2018-06-19 14:25 UTC, benel commented on features/step_definitions/comment.rb
> +    delete_button = all("._54nh")[2]
idem.

2018-06-20 20:00 UTC, benel commented
Your commits are really strange (only merge commits with no files changed)... Please make a clean new pull request.

2018-06-20 20:00 UTC, closed without merging