Item creation
Hypertopic/Porphyry pull request #195
Opened 2019-06-06 08:50 UTC by louisVHZ

## Content

Ajout de la fonctionnalité "Create an item" avec ses tests.

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2019-06-14 13:45 UTC, benel commented on features/step_definitions/item.rb
> +require 'selenium/webdriver'
Please don't change the development environment. It makes tests on the continuous integration server to fail.

2019-06-14 13:45 UTC, benel commented on features/step_definitions/item.rb
> +Capybara.default_driver = :selenium_chrome_headless
Idem.

2019-06-14 13:51 UTC, benel requested changes
The tests fail on Travis.
Please note that you updated tools settings to conform your local configuration... Therefore it cannot work on the continuous integration server.
Please try to base your 2 commits on v7 HEAD (and remove your local hacks).
Hopefully it will work.

2019-06-17 17:41 UTC, benel requested changes
Thank you for your contribution to Porphyry.
To be integrated, several changes in your code are needed however.
Thank you for taking into account every comments I made.

2019-06-17 17:41 UTC, benel commented on features/step_definitions/portfolio.rb
> +  find_button('Ajouter un attribut').click
Be careful the user interface has changed. Please modify the test accordingly.

2019-06-17 17:41 UTC, benel commented on features/step_definitions/portfolio.rb
> +require 'selenium/webdriver'
Please don't change the development environment. It makes tests on the continuous integration server to fail.

2019-06-17 17:41 UTC, benel commented on features/item_creation.feature
> +#Maxime TRINQUARD
Authors credits are already in  the commit messages. There is no need to add them to the source files.

2019-06-17 17:41 UTC, benel commented on features/step_definitions/portfolio.rb
> +Capybara.default_driver = :selenium_chrome_headless
Please don't change the development environment. It makes tests on the continuous integration server to fail.

2019-06-17 17:41 UTC, benel commented on features/item_creation.feature
> +Quand l'utilisateur clique sur le bouton de création d'item à coté du corpus "Vitraux - Bénel" pour creer un item "Vitraux Test"
In the scenario, each step should be related to data, not to the user interface.

2019-06-17 17:41 UTC, benel commented on features/item_creation.feature
> +Alors l'item "Vitraux Test" est affiché
This sample data is not realistic.

2019-06-19 13:20 UTC, louisVHZ commented
@Jadestanzie @nhuchon @maxiloud 
Est-ce qu'un d'entre vous peut s'occuper de faire passer les tests pour cette fonctionnalité parce que j'arrive pas à lancer les tests sur ma machine ?
Quand les tests passeront je nettoierai les commits et on pourra merge cette branche dans le dépot officiel Porphyry.

2019-06-19 18:55 UTC, nhuchon commented
@louisVHZ je viens de modifier le test, tu avais mis la connexion avant d'afficher la page, j'ai donc du changer l'ordre pour que cela soit fonctionnel

2019-06-19 20:06 UTC, louisVHZ commented
@nhuchon ah d'accord je comprenais pas, merci !

2019-06-20 07:35 UTC, nhuchon commented
Attention @louisVHZ, j'ai remodifier le test car tu avais inclut une erreur lors du merge, il faudrait maintenant clean les commits

2019-06-20 14:05 UTC, louisVHZ commented
@nhuchon Est-ce que tu peux vérifier sur ta machine en faisant un "git pull" que les tests passent bien ?

2019-06-20 14:15 UTC, nhuchon commented
je fais ça dès que je le peux, je suis en train de faire la pull request de l'algèbre booleen, mais j'aurais besoin du mail associé a ton compte pour te mettre en co-auteur

2019-06-20 15:19 UTC, nhuchon commented
@louisVHZ L'ensemble des tests sont fonctionnels chez moi

2019-06-20 15:43 UTC, louisVHZ commented
@benel On vient de terminer les changements sur cette fonctionnalité. Il ne reste plus que votre validation pour merger la pull request.

2019-06-21 04:20 UTC, merged