TEST: Select items according to a given attribute (#158)
Hypertopic/Porphyry pull request #335
Opened 2020-05-23 09:32 UTC by Kodlah

## Content

Test for the ticket #158 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-05-27 07:52 UTC, benel requested changes
Merci de cette contribution.

En plus des commentaires ligne à ligne, quelques conseils pour améliorer le test : 

- [ ] À propos du **nom du fichier** `attribute_browse.feature`, notez qu'il s'agirait : 
  - plus d'une recherche (`search`) que d'un feuilletage (`browse`),
  - le fait de le rattacher plutôt au `portfolio` qu'à l'attribut (`attribute`) permettrait de le regrouper à terme avec un test sur la recherche par catégorie (autre cas), ainsi que de montrer qu'il s'agit d'une alternative au feuilletage.

  Je vous recommande donc plutôt : `portfolio_search.feature`.

- [ ] Pour le scénario, même s'il est effectivement utile de l'avoir fait au départ pour votre situation d'usage (pour être sûr que vous avez besoin du comportement testé, et pour votre démonstration dans la vidéo finale), notez que le test ne pourra passer que si vous **l'adaptez au cas des vitraux** (car c'est le jeu de données utilisé par les autres tests sur le serveur d'intégration continue et que ça vous demanderait énormément de travail de configurer un autre environnement de test).

- [ ] Si vous voulez éviter de faire échouer le test, en attendant l'implémentation de la fonctionnalité correspondante, vous pouvez ajouter `pending` suivi par exemple de  `"To be implemented"`. Cela préviendra le logiciel de test que l'échec du test est "normal" pour l'instant.

2020-05-27 07:52 UTC, benel commented on features/step_definitions/event.rb
> +    click_on class: 'ValidateButton'
Merci de n'ajouter des lignes à votre contribution que si elles sont en lien avec votre sujet : 

- cela minimise les risques de conflit au moment des fusions,
- cela permet de mieux comprendre un fichier en observant les couches d'écriture de chaque ligne (cf. [exemple](https://github.com/Hypertopic/Porphyry/blame/v7/features/attribute_set.feature)),
- cela rend plus facile les annulations (`revert`),
- etc.

2020-05-27 07:52 UTC, benel commented on features/step_definitions/event.rb
> +Quand("{string} est inscrit dans la barre de recherche et on clique sur {string}") do |value1,value2|
"Barre de recherche" et "cliquer" font référence à des choix d'interface. Or ceux-ci sont déjà présents dans l'implémentation des tests qui suit.
De sorte que les scénarios restent inchangés si l'interface change, montez en abstraction dans la formulation de l'action.

2020-05-27 07:52 UTC, benel commented on features/step_definitions/outcome.rb
> +Alors("le dessin {string} est affiché") do |value|
Le logiciel est générique, donc la formulation des étapes doit l'être aussi : il ne doit pas être question de "dessins", de "vitraux", d'"UE", de "témoignages"... mais d'**items**.
Avec un peu de chance, l'étape existe déjà.

2020-05-27 18:05 UTC, Kodlah commented
J'ai bien pris en compte vos indications et effectué les changements nécessaires. 
En espérant que le test a été amélioré correctement.

2020-06-04 06:29 UTC, benel commented on features/portfolio_search.feature
> +Quand on met "2017" dans la barre de recherche et on clique sur "Created : 2017"
J'ai l'impression que vous avez modifié l'étape dans la partie test mais pas dans la partie scénario... Ou peut-être est-ce un bug d'affichage de GitHub ?
Quoi qu'il en soit, merci de fusionner les deux commits en un seul.

2020-06-04 06:30 UTC, benel requested changes
J'ai l'impression que vous avez modifié l'étape dans la partie test mais pas dans la partie scénario... Ou peut-être est-ce un bug d'affichage de GitHub ?
Quoi qu'il en soit, merci de fusionner les deux commits en un seul.

2020-06-04 08:26 UTC, Kodlah commented on features/portfolio_search.feature
> +Quand on met "2017" dans la barre de recherche et on clique sur "Created : 2017"
Je crois que c'est parce que je n'ai pas renommé le fichier en question mais j'en ai crée un nouveau. Vous m'aviez demandé de changer le nom du fichier de scénario et de faire le scénario pour l'environnement des vitraux.

2020-06-04 08:27 UTC, Kodlah commented
> Quoi qu'il en soit, merci de fusionner les deux commits en un seul.

Normalement, les commits ont été fusionnés.

2020-06-11 09:46 UTC, closed without merging