FIX: Topics could be displayed before occurences can be computed (closes #212)
Hypertopic/Porphyry pull request #338
Opened 2020-05-25 17:13 UTC by garnier5

## Content

Topics are displayed before the occurrences are loaded 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-05-27 12:34 UTC, benel requested changes
Pourquoi votre titre de commit ne contient-il pas `closes` ?

2020-05-27 12:34 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +      .then(x => this.state.corpora.map(y => `/corpus/${y.id}`))
Pour indiquer au lecteur que `x` n'est pas utilisé. Ce serait mieux de le remplacer par `()`.

2020-05-27 12:38 UTC, benel commented
Le fait qu'un de vos `then` n'utilise pas son paramètre d'entrée montre que votre séquence est arbitraire par moments. Il faudrait que vous que ouvriez un nouveau ticket sur l'amélioration de la parallélisation des étapes de `_fetchAll`. Quand vous l'aurez fait, je vous recommande de faire un petit diagramme de tâche pour déterminer entre les étapes ce qui doit être en séquence et ce qui peut être parallélisé.

2020-05-27 12:48 UTC, garnier5 commented
> Il faudrait que vous que ouvriez un nouveau ticket sur l'amélioration de la parallélisation des étapes de _fetchAll.

N'est-il pas étrange d'ouvrir un ticket en réponse à ce pull request qui ne sera jamais mis en production sous cette forme ?

2020-05-27 12:51 UTC, benel commented
> N'est-il pas étrange d'ouvrir un ticket en réponse à ce pull request qui ne sera jamais mis en production sous cette forme ?

Ah bon ? Vous ne souhaitez plus que je l'intègre ?

2020-06-04 18:07 UTC, benel commented
> Ah bon ? Vous ne souhaitez plus que je l'intègre ?

Je viens de comprendre... La demande d'intégration #342 vient remplacer celle-ci et non l'améliorer. C'est bien cela ?

2020-06-04 18:07 UTC, closed without merging