FEATURE: Select items according to a given attribute (see #158)
Hypertopic/Porphyry pull request #343
Opened 2020-05-30 17:13 UTC by Kodlah

## Content

Nous avons commencé avec @macchrd à développer la fonctionnalité. Désormais les noms et valeurs des attributs s'affichent dans la barre de recherche. 
Cependant, nous n'avons pas encore réussi à faire en sorte de rediriger l'utilisateur vers un résultat filtré selon la valeur de l'attribut sélectionné. 
En effet, quand on clic sur une suggestion, rien ne s'affiche avec la mention "Thème inconnu" sur la page. Ce qui est normal dans la mesure où nous avons utilisé des 'id' fictifs pour les candidats. 
Nous pensons qu'il y a un travail à réaliser au niveau du fichier "Status.jsx" mais nous ne savons pas du tout comment nous y prendre. 
Pourriez-vous nous éclairer ? 

Voici le rendu actuel : 
![created](https://user-images.githubusercontent.com/26245304/83334845-8d2e0e80-a2a9-11ea-8d60-b3f0516b49bf.PNG)

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-05-30 17:34 UTC, benel commented
> Nous pensons qu'il y a un travail à réaliser au niveau du fichier "Status.jsx" mais nous ne savons pas du tout comment nous y prendre.

L'implémentation peut se découper en plusieurs étapes : 

- [x] afficher les attributs-valeurs parmi les candidats (Bravo 🥳), 
- [ ] en fonction du "candidat" sélectionné, [modifier l'URI](https://github.com/Hypertopic/Porphyry/blob/7af65e9d5a963623f66e44758ff5732e61410cc1/src/components/portfolioPage/SearchBar.jsx#L39-L46) (il vous faudra pour cela comprendre la structure inventée par les étudiants de l'an dernier pour la sélection de topics avec des ET, des OU et des NON, et voir comment vous pourriez y ajouter des attributs),
- [ ] afficher effectivement dans la barre de statut les attributs demandés dans l'URI,
- [ ] tenir compte des attributs indiqués dans l'URI pour [filtrer les items](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/Portfolio.jsx#L124) en conséquence.

2020-06-03 19:34 UTC, Kodlah commented
L'implémentation selon vos étapes est terminé : 
 
* [x]  afficher les attributs-valeurs parmi les candidats.

* [X]  en fonction du "candidat" sélectionné, modifier l'URI.

* [X]  afficher effectivement dans la barre de statut les attributs demandés dans l'URI,
 
* [X]  tenir compte des attributs indiqués dans l'URI pour filtrer les items.

Pouvez-vous confirmer que cela fonctionne de votre côté ?

2020-06-09 07:18 UTC, benel requested changes
Merci pour cette contribution @Kodlah !

J'ai testé la fusion de votre branche avec la branche courante. La fonctionnalité elle-même est utilisable (bravo !) mais attention : 

- [ ] il y a une incohérence entre les étapes employées dans vos scénarios Cucumber et celles définies dans vos tests Capybara.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/597307/84116717-a3b63180-aa30-11ea-8fb6-c7b3277f1ab0.png">

- [ ] vous avez **cassé une fonctionnalité existante** (vous pouvez tester le scénario à la main, vous verrez que ça crée une exception sur une de vos lignes de code, probablement l'attribut recherché qui a une valeur nulle) : 
<img width="761" alt="Capture d’écran 2020-06-09 à 09 04 51" src="https://user-images.githubusercontent.com/597307/84116536-4e7a2000-aa30-11ea-965c-d5dc7d864187.png">

J'avais aussi fait une relecture "statique" de votre code hier sous forme de commentaires. Vous verrez ce qui est applicable. Notamment, mon conseil de partir d'une sélection thématique avant de passer à une recherche par attribut n'est hélas pas applicable à ce code. C'est dommage pour les scénarios, mais je pense que ça va au-delà de ce ticket : il s'agirait d'un nouveau ticket de FIX qui consisterait à considérer la recherche (de catégorie ou d'attribut) non pas comme une nouvelle sélection mais comme un critère supplémentaire pour la sélection actuelle .

Pensez bien à faire votre livraison sous forme de deux contributions (_commits_), une pour le test, une pour la fonctionnalité (avec pour chacun•e les [co-auteurs éventuels](https://help.github.com/articles/creating-a-commit-with-multiple-authors/).

2020-06-09 07:18 UTC, benel commented on features/portfolio_search.feature
> +Soit "vitraux" le portfolio ouvert
Si possible, prenez une page d'accueil plus "ciblée". Cela permet de réduire les risques de "time out" quand on lance les tests (ceux en lecture seule) sur le serveur de production. Vous pouvez vous inspirer en cela de [la première phrase du premier scénario du browsing de portfolio](https://github.com/Hypertopic/Porphyry/blob/v7/features/portfolio_browse.feature#L7).

2020-06-09 07:18 UTC, benel commented on features/portfolio_search.feature
> +Quand on met "2017" dans la barre de recherche et on clique sur "Created : 2017"
- [ ] Reformulez l'étape de manière à ce qu'elle soit indépendante de l'interface... Si demain par exemple Porphyry est disponible sur un assistant vocal, ce sera la même fonctionnalité mais avec une interface vocale (par exemple, dans la première partie de votre action "mettre dans la barre de recherche" c'est tout simplement "chercher"), 
- [ ] Vérifiez que ça fonctionne avec les données disponibles sur le serveur de test (je pense par exemple que dans la **deuxième** chaîne de caractère vous devez avoir une date complète).

2020-06-09 07:18 UTC, benel commented on features/step_definitions/event.rb
> +    click_on class: 'ValidateButton'
Même si vos modifications de "style" sont légitimes, évitez de les intégrer à des commits qui n'ont rien à voir. 

1. Cela complique terriblement le travail de l'intégrateur (ça peut génèrer de manière artificielle des "conflits").
2. Ça réduit l'intéret d'autres commandes de Git, comme `git blame` ([exemple](https://github.com/Hypertopic/Porphyry/blame/v7/src/components/portfolioPage/Portfolio.jsx)) qui sont formidablement pratique pour "documenter" le code (comprendre pour quelle fonctionnalité ou fix on ajouté une partie de code). Mais aussi, par exemple `git revert` (si on décide finalement qu'on ne veut pas votre fonctionnalité, ça ne veut pas dire que l'on ne veuille pas vos corrections de style)...

2020-06-09 07:18 UTC, benel commented on features/step_definitions/event.rb
> +  pending "To be implemented"
Comme vous allez réécrire l'historique et envoyer les deux commits d'un coup, vous pouvez supprimer le "pending".

2020-06-09 07:18 UTC, benel commented on features/step_definitions/event.rb
> +Quand("l'utilisateur indique {string} et sélectionne {string}") do |value1,value2|
Donnez un nom plus explicite à `value1` et `value2`.

2020-06-09 07:18 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +
N'ajoutez une ligne que si ça ne peut pas fonctionner sans elle.

2020-06-09 07:18 UTC, benel commented on src/components/portfolioPage/SearchBar.jsx
> +    );
Attention à vos indentations : vous avez un décalage de trop (2 espaces). 

D'ailleurs, le code a-t-il été validé avec `eslint` sur votre poste ?
Sur le serveur d'intégration, la validation du style ne passe pas : 
https://travis-ci.org/github/Hypertopic/Porphyry/builds/694390859#L243

2020-06-10 10:07 UTC, Kodlah commented
Bonjour Monsieur, 

J'ai pris en compte vos remarques et j'en ai corrigé certaines. Je suis en train d'essayer de faire passer le test d'acceptation mais je suis bloqué...
En effet, j'essaye de faire en sorte de récupérer l'élément de la SearchBar afin de mettre ma première valeur. Mais malgré tout ce que j'écris, Capybara ne trouve pas l'élément : 

Test : 
![scen](https://user-images.githubusercontent.com/26245304/84255222-9a04fa80-ab12-11ea-9470-2172e593a3aa.PNG)

Cucumber :
![capy](https://user-images.githubusercontent.com/26245304/84255308-b6a13280-ab12-11ea-9bc6-a6faad6a4201.PNG)

2020-06-11 07:22 UTC, benel commented
@Kodlah Plutôt que `fill_in` qui est une action de "haut niveau" des champs de formulaire, essayez plutôt de simuler le fait de presser les touches avec `send_keys`.

En effet, le composant dans lequel vous écrivez n'a plus tout à fait le comportement d'un champ de formulaire normal.

Vous en avez un exemple dans [cette étape](https://github.com/Hypertopic/Porphyry/blob/v7/features/step_definitions/event.rb#L47) d'un autre scénario. Comme cette autre fonctionnalité utilise le même composant de suggestion, ça devrait fonctionner sans problème.

2020-06-15 09:13 UTC, benel commented
> nous avons toujours six scénarios qui ne passent pas avec toujours l'erreur mentionnée ci-dessous du Unable to find css

@Kodlah Si vos tests échouent c'est à cause de cas limites qui ne sont pas gérés par votre code (notamment quand l'attribut sélectionné n'est pas défini). Vous pouvez vous en rendre compte facilement en faisant les tests à la main.

Par exemple, pour `À partir d'un item, obtenir ceux qui sont dans la même rubrique`, voici ce que cela donne dans le navigateur : 
![image](https://user-images.githubusercontent.com/597307/84639597-e1b3c980-aef8-11ea-96c6-904ac369a7da.png)

C'est ce message d'erreur de React qui cache la page et donc rend  introuvable l'élément HTML identifié par le sélecteur CSS du test.

2020-06-17 17:41 UTC, benel commented
Feature is implemented and integrated.

2020-06-17 17:41 UTC, closed without merging