TEST: Select items according to a given attribute (#158)
Hypertopic/Porphyry pull request #344
Opened 2020-06-04 14:16 UTC by ValentinLouerat

## Content

Test ticket #158 
Nous ne sommes pas certains de la validité de ces tests car nous ne pouvons pas les tester en local, nous attendons donc vos retours avec impatience. Bonne journée

effectué avec @line-tan @EmileReyUL 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-04 14:22 UTC, benel commented
> Nous ne sommes pas certains de la validité de ces tests car nous ne pouvons pas les tester en local, nous attendons donc vos retours ave impatience. 

On le saura effectivement quand la fonctionnalité et l'étape de test sera implémentée...

Par contre, on peut améliorer votre scénario. Ce qui me chiffonne c'est que AXN 002 est déjà affiché (avant la recherche). Du coup, il faudrait vous intéresser à **deux** items : un qui sera caché par la sélection et l'autre qui demeurera affiché.

2020-06-04 14:24 UTC, benel commented
Et si possible, réutilisez dans votre scénario des items qui sont déjà sur le serveur de test : ça évitera d'avoir à en ajouter à la base de test.

2020-06-04 14:53 UTC, EmileReyUL commented
> > Nous ne sommes pas certains de la validité de ces tests car nous ne pouvons pas les tester en local, nous attendons donc vos retours ave impatience.
> 
> On le saura effectivement quand la fonctionnalité et l'étape de test sera implémentée...
> 
> Par contre, on peut améliorer votre scénario. Ce qui me chiffonne c'est que AXN 002 est déjà affiché (avant la recherche). Du coup, il faudrait vous intéresser à **deux** items : un qui sera caché par la sélection et l'autre qui demeurera affiché.

@benel nous sommes en train de faire une nouvelle tentative pour qu'elle soit validée, nous n'avions pas vu votre réponse. Nous prendrons en compte vos conseils dans la tentative suivante, merci !

2020-06-04 15:06 UTC, ValentinLouerat commented
Bonjour, après quelques galères avec git ^^ je m'en suis sorti pour push convenablement. Je ne sais plus exactement quelle version vous aviez vu, pourriez vous voir si vos remarques sont toujours d'actualité ? Pouvez-vous expliciter aussi comment savoir si les items sont sur le serveur de test ? car j'ai pris un item présent sur la version en production mais je ne sais comment accéder à la version de test.
Très bonne soirée !

2020-06-04 15:37 UTC, benel requested changes
Pour répondre à votre question, voici quelques commentaires en contexte.

Voilà sinon, il y avait aussi l'idée d'avoir deux items et de les regarder avant et après l'action.

2020-06-04 15:37 UTC, benel commented on features/portfolio_search.feature
> +Quand l'utilisateur tape "Auxon" dans la searchbar et ensuite clique sur "spatial > Eglise Saint-Loup, Auxon"
Le principe est bon (les deux données entre guillemets sont parfaites), mais ce serait mieux si la phrase restait valide malgré un changement d'interface (imaginez par exemple que ça puisse aussi se faire à la voix).

2020-06-04 15:37 UTC, benel commented on features/step_definitions/event.rb
> +    click_on class: 'ValidateButton'
Même si la suppression de cet espace final est une bonne idée dans l'absolu, il faut éviter de les ajouter dans un commit thématique. Quand on le fait souvent ça peut considérablement compliquer l'intégration de plusieurs branches (en générant de nombreux conflits). Ça rend aussi moins utilisable la fonctionnalité `git blame si` utile (voir [exemple](https://github.com/Hypertopic/Porphyry/blame/ed68dde008b3e94392d7932bca4953a3cacd62a6/features/step_definitions/event.rb)).

Si vous utilisez une interface pour faire vos commits (comme Atom), c'est facile de choisir les lignes que vous intégrez au commit et celles que vous n'intégrez pas.

Concrètement, ça veut dire que pour ces modifications mineures de "style de codage" on attendra un commit spécialisé sur cela.

2020-06-04 15:42 UTC, benel commented
> Pouvez-vous expliciter aussi comment savoir si les items sont sur le serveur de test ? 

Le plus simple est de lancer Porphyry à partir des sources (`npm start`).

En gros, pour les items affichés, ça donne ceci : 

<img width="770" alt="Capture d’écran 2020-06-04 à 15 38 43" src="https://user-images.githubusercontent.com/597307/83777924-4b76dc80-a68a-11ea-93c3-6679fab4d583.png">

[Bien entendu les `SMV 129` ne font pas partie du jeu de test, ils ont été générés par le test de création d'un item.]

Vous pouvez aussi retrouver ces items dans les autres scénarios...

2020-06-04 15:42 UTC, benel commented
Bonne soirée à vous également.

2020-06-11 12:29 UTC, ValentinLouerat commented
Alors nous venons de faire la modification de la phrase de présentation, nous nous occupons actuellement de changer les données pour qu'elles coïncident avec celles du serveur de test. Cependant en lançant le projet, nous n'avons aucune donnée donc on ne peut pas aller voir les attributs des différents items. Pourtant le fichier public/config.yml nous parait juste et est bien connecté à http://argos2.test.hypertopic.org.
Cependant quand on essaie de le mettre dans l'url cela nous renvoie error:timeout, est-ce normal ?

pourriez vous nous donner les attributs de deux items du serveur de test afin de pouvoir faire nos tests ?

2020-06-11 12:33 UTC, ValentinLouerat commented
De plus nous allons attaquer l'histoire d'échapper la ligne avec l'espace pour le commit, cependant nous aimerions savoir pourquoi nous avons un message de conflit sur ce pull request (This branch has conflicts that must be resolved, Only those with write access to this repository can merge pull requests. Conflicting files : features/step_definitions/event.rb) ? car il nous semble que cela fait échouer les tests d'intégration continue. Est-ce normal, si non que devons nous faire ? car dans le conflit il y a en jeu du code que nous n'avons pas écrit et on ne voudrait pas le supprimer

2020-06-11 12:51 UTC, EmileReyUL commented
Voici notre nouveau commit.
(ne prêtez pas attention aux différents comptes utilisés, j'ai eu du mal à utiliser les bonnes clés SSH et j'ai commit avec mon ancien compte GitHub Student que j'utilisais quand j'étais en DUT, je travaille bien avec le compte @EmileReyUL)

Nous (@ValentinLouerat  et moi même) avons réglé le commit qui posait problème avec l'espace en fin de ligne, et nous avons modifié la phrase pour laquelle vous aviez fait une remarque.

2020-06-11 13:40 UTC, benel commented
> Enfin nous attendons votre confirmation pour résoudre le conflit

@ValentinLouerat @EmileReyUL  Est-ce que vous voyez aussi le message complet : 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/597307/84391756-af088900-abf9-11ea-822c-cf36ba8e98f3.png">

En cliquant sur "command line" vous avez la suite de commandes à faire avec git.

2020-06-11 13:40 UTC, benel commented
Quoique non, ce sont les commandes de l'intégrateur... Pas du développeur...

2020-06-11 13:41 UTC, benel commented
L'idée est de mettre à jour votre branche v7. Puis de tenter un rebase ou un merge (mais dans ce cas vers votre branche). Je ne sais pas si c'est clair...

2020-06-11 13:52 UTC, ValentinLouerat commented
ok on va tester ça

2020-06-11 16:06 UTC, benel commented
@ValentinLouerat On peut aussi utiliser l'interface graphique de GitHub comme je le décris dans la discussion.

2020-06-15 13:03 UTC, benel commented
@ValentinLouerat Merci de vous rapprocher de l'équipe de @FirielEinor qui a travaillé sur le même scénario/test. En prenant ce qu'il y a de mieux dans vos deux équipes, ce sera parfait.

2020-06-15 13:56 UTC, FirielEinor commented
@ValentinLouerat Je vous poste ici notre scénario pour que l'on puisse le mélanger avec vos test :

Fonctionnalité: Sélectionner un item selon un attribut donné

Scénario :

  Soit "Abram/Abraham" les rubriques sélectionnées
  Et "PSM 002" un des items affichés
  Et "SJ 001" un des items affichés
  Et "SM 001 m" un des items affichés
  Et "SM 001 n" un des items affichés
  Et "SM 008 g" un des items affichés
  Et "SNZ 005" un des items affichés
  Et "SNZ 006" un des items affichés
  Et "SR 005" un des items affichés
  Quand l'attribut "Spatial : Pont-Sainte-Marie" est sélectionné
  Alors "PSM 002" est affiché
  Et "SJ 001" n'est pas affiché
  Et "SM 001 m" n'est pas affiché
  Et "SM 001 n" n'est pas affiché
  Et "SM 008 g" n'est pas affiché
  Et "SNZ 005" n'est pas affiché
  Et "SNZ 006" n'est pas affiché
  Et "SR 005" n'est pas affiché

2020-07-03 12:50 UTC, benel commented
Intégré sous la forme d'un "best-of" de vos trois propositions (#358, #344 et #328) : 357770fea37705bf55618a81cc41d6a6f1cbd6f2.

2020-07-03 12:50 UTC, closed without merging