TEST: Create a bidirectional link between two items (see #188)
Hypertopic/Porphyry pull request #346
Opened 2020-06-06 14:51 UTC by ChloeChamaillard

## Content

Nous ne sommes pas certains de la validité de ces tests car nous ne pouvons pas les tester en local, nous attendons donc vos retours avec impatience. Bonne journée

effectué avec @tinidec 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-09 07:41 UTC, benel requested changes
Merci pour cette contribution.

Vos scénarios et tests sont plutôt pas mal mais il y a des petites erreurs à corriger.

2020-06-09 07:41 UTC, benel commented on features/step_definitions/context.rb
> +  visit getURI(itemName)
Si vous faites comme ça, vous allez modifier par la suite le "vrai" `SNZ 006`, celui de référence qui sert à tous les autres tests... Même si en théorie vous n'écrasez pas ses données existantes, c'est un peu risqué.
Utilisez plutôt l'étape existante qui crée un item avec un identifiant aléatoire.

2020-06-09 07:41 UTC, benel commented on features/step_definitions/event.rb
> +    click_on class: 'ValidateButton'
Même si la suppression de cet espace final est une bonne idée dans l'absolu, il faut éviter de les ajouter dans un commit thématique. Quand on le fait souvent ça peut considérablement compliquer l'intégration de plusieurs branches (en générant de nombreux conflits). Ça rend aussi moins utilisable la fonctionnalité git blame si utile (voir [exemple](https://github.com/Hypertopic/Porphyry/blame/ed68dde008b3e94392d7932bca4953a3cacd62a6/features/step_definitions/event.rb)).

Si vous utilisez une interface pour faire vos commits (comme Atom), c'est facile de choisir les lignes que vous intégrez au commit et celles que vous n'intégrez pas.

Concrètement, ça veut dire que pour ces modifications mineures de "style de codage" on attendra un commit spécialisé sur cela.

2020-06-09 07:41 UTC, benel commented on features/step_definitions/event.rb
> +Quand ("l’utilisateur choisit l’item {string} dans la liste") do |itemName|
Quelle liste ? Essayez d'être un peu plus explicite...
Si c'est vrai que vous avez pensé cette étape dans un scénario (donc dans un contexte donné où il n'y a pas d'ambiguïté), la définition, elle, est indépendante de tout contexte.

2020-06-09 07:41 UTC, benel commented on features/step_definitions/outcome.rb
> +  visit getURI(item)
Le `Alors` est un contrôle, pas une action : ce n'est pas lui qui est censé vous emmener sur cette page. 
Ce que vous devez vérifier c'est que vous êtes sur la bonne page (par exemple en vérifiant le titre – c'est-à-dire le contenu de `.Subject`).

2020-06-09 07:44 UTC, benel commented
Vous apparaissez comme votre propre co-auteur... La syntaxe des co-auteurs n'est à utiliser que pour d'éventuels co-auteurs **autres** que l'auteur principal du commit (dans le cas par exemple où vous l'auriez fait en binôme).

2020-06-11 08:47 UTC, ChloeChamaillard commented
Je ne sais pas pourquoi je suis co-auteur de moi-même, j’ai ce problème depuis le début du semestre. A chaque commit, je suis à la fois auteur principale et co-auteur.

2020-06-11 09:05 UTC, benel commented
> Normalement, le problème de co-auteur est résolu

Oui, effectivement. Vous aviez un paramètre bizarre dans votre configuration de Git ?

2020-06-11 09:07 UTC, benel commented
@ChloeChamaillard Visiblement, vous avez tenu compte de toutes mes remarques. Super !

Il ne vous manque qu'à fusionner les deux commits en un seul. Vous voyez comment faire ?

2020-06-11 09:09 UTC, benel commented
> effectué avec @tinidec

Ça n'apparaît pas dans le commit. Pensez à utiliser la syntaxe adéquate dans le texte de votre commit.

Par ailleurs, vous parlez uniquement de la partie "test" ou également de la partie scénario ?

2020-06-11 09:11 UTC, benel commented
Enfin il faudra penser à résoudre les conflits d'édition que vous avez avec les modifications déjà intégrées des autres étudiants (ça devrait être facile, c'est juste que Git a cru que vous utilisiez le même `end` alors qu'évidemment chacun a le sien).

2020-06-11 09:43 UTC, ChloeChamaillard commented
> Il ne vous manque qu'à fusionner les deux commits en un seul. Vous voyez comment faire ?
Je ne sais plus si c'est avec git reset soft ou git rebase -i

2020-06-11 09:44 UTC, ChloeChamaillard commented
> Par ailleurs, vous parlez uniquement de la partie "test" ou également de la partie scénario ?

Pour les scénarios, c'était avec @gabyseg et les tests avec @tinidec

2020-06-11 09:46 UTC, benel commented
> Je ne sais plus si c'est avec git reset soft ou git rebase -i

Il y a souvent plusieurs manières de faire, mais dans Git-Graal nous avons utilisé effectivement `git reset --soft` pour enlever des commits (ici un seul) et `git --amend` pour modifier celui qui reste (ajouter des modifications, changer les co-auteurs, etc.).

2020-06-11 11:58 UTC, ChloeChamaillard commented
> Enfin il faudra penser à résoudre les conflits d'édition que vous avez avec les modifications déjà intégrées des autres étudiants (ça devrait être facile, c'est juste que Git a cru que vous utilisiez le même `end` alors qu'évidemment chacun a le sien).

Où et comment on peut résoudre les conflits d'édition ?

2020-06-11 13:52 UTC, benel commented
Sur les conflits, vous êtes plusieurs a poser la question, je vais essayer de faire un topo dans les discussions...

2020-06-11 13:53 UTC, benel commented
@ChloeChamaillard Est-ce que vous avez accès au gros bouton "Resolve conflicts" ?

2020-06-11 13:54 UTC, ChloeChamaillard commented
> @ChloeChamaillard Est-ce que vous avez accès au gros bouton "Resolve conflicts" ?

Oui

2020-06-11 14:25 UTC, ChloeChamaillard commented
@benel Est-ce que je dois fusionner les 2 commits en un seul ?

2020-06-11 14:29 UTC, benel commented
> Est-ce que je dois fusionner les 2 commits en un seul ?

Comme c'est un commit de merge, non.

D'abord cela ferait un très gros commit un peu incompréhensible.

Par ailleurs, on peut automatiquement cacher ces commits de merge dans certaines commandes de git (ex : `git log --no-merges`).

2020-06-30 17:06 UTC, benel commented on features/items_with_link.feature
> +Fonctionnalité : Créer un lien bidirectionnel entre deux items
Pour que ça fonctionne avec Cucumber, il faudrait supprimer l'espace avant `:` (oui, Cucumber ne sait pas gérer les règles typographiques françaises).

2020-06-30 17:07 UTC, benel commented on features/items_with_link.feature
> +Scénario : À partir d'un item, obtenir ceux qui sont similaires
Pour que ça fonctionne avec Cucumber, il faudrait supprimer l'espace avant `:` (oui, Cucumber ne sait pas gérer les règles typographiques françaises).

2020-06-30 17:14 UTC, benel commented
Votre scénario de test est plutôt bien. Je vais le mettre en "draft" (puisque l'implémentation n'est pas pour tout de suite).

Notez qu'il pourrait arriver qu'il y ait plusieurs items qui portent le même nom. On s'attendrait alors à avoir des suggestions avec par exemple, les vignettes ou un autre attribut qui permettrait de les distinguer.

Le commit mentionne @ChloeChamaillard,  @tinidec et @gabyseg. 
Plus précisément, comment vous êtes vous répartis le travail entre le scénario et les tests ?

2020-07-01 17:22 UTC, ChloeChamaillard commented
> Le commit mentionne @ChloeChamaillard, @tinidec et @gabyseg.
> Plus précisément, comment vous êtes vous répartis le travail entre le scénario et les tests ?

Pour les scénarios : @gabyseg et @ChloeChamaillard
Et les tests : @tinidec et @ChloeChamaillard

2021-06-21 15:49 UTC, closed without merging