FEATURE: Look at thumbnails of items with the same name (closes #66)
Hypertopic/Porphyry pull request #348
Opened 2020-06-07 16:35 UTC by JosephNM

## Content

Fonctionnalité de viualisation des vignettes des items Ayant le même nom dans la page item. 

Remarques: 
-Les vignettes visibles sont cliquables et mènent vers les pages des items associés. 
-Un item ayant le même nom mais n'ayant pas de vignette ne sera pas accessible à partir de la page item. 
---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-07 20:06 UTC, JosephNM commented
Vu que les tests marchent, je suppose que je devrais cocher les cases acceptance tests et implémentation du kanban, sauf que j'ai l'impression de ne pas avoir le droit de cocher ces cases.

2020-06-08 06:53 UTC, benel commented on src/components/itemPage/Item.jsx
> +              </div>
Est-ce pour la mise en page, cette `div` vide ?

2020-06-08 06:55 UTC, benel commented on src/components/itemPage/SameNameBlock.jsx
> +    <div className="Item">
- Une `div` sans rien dedans, pourquoi l'afficher ?
- En l'absence de vignette; ne pourrait-on pas ancrer le lien sur autre chose ?

2020-06-08 06:57 UTC, benel commented on src/components/itemPage/Item.jsx
> +import SameNameBlock from './SameNameBlock.jsx';
Pourquoi est-ce dans le commit de test et non dans celui de l'implémentation ?

2020-06-08 06:57 UTC, benel commented on src/components/itemPage/Item.jsx
> +              </div>
Pourquoi est-ce dans le commit de test et non dans celui de l'implémentation ?

2020-06-08 06:57 UTC, benel commented on src/components/itemPage/Item.jsx
> +              <SameNameBlock ID={this.props.match.params.item} item={this.state.item} />
Pourquoi est-ce dans le commit de test et non dans celui de l'implémentation ?

2020-06-08 07:02 UTC, benel requested changes
Joli travail @JosephNM !

Comme vous le verrez dans le code, avant de l'intégrer, j'ai quelques dernières demandes de modification.

Par ailleurs, dans les deux commits vous apparaissez comme l'unique auteur. Si c'est le cas, pas de problème. Si par contre vous les avez fait en binôme (peut-être même dans un binôme différent dans l'un et l'autre commit), pensez à les mentionner avec la [syntaxe GitHub](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors)).

2020-06-08 07:06 UTC, JosephNM commented on src/components/itemPage/SameNameBlock.jsx
> +    <div className="Item">
Initialement, je pensais que sans vignette, le nom de l'item devrait être affiché et pointer vers la page de cet item (dans les cas d'utilisation de Porphyry comme Musique en Synoptique). Mais en lisant le titre je me suis dis que ce cas d'usage ferait l'objet d'un autre ticket. À tord au vu de votre remarque...

2020-06-08 07:07 UTC, JosephNM commented on src/components/itemPage/Item.jsx
> +              </div>
En effet, afin de respecter l'espace défini dans les maquettes.

2020-06-08 07:30 UTC, JosephNM commented
Merci @benel 

Pour toutes les remarques qui relèvent du commit du fichier item.jsx, honnêtement je ne saurais pas vous donner d'explications valables parce que quand je faisais des git add pour les fichiers du commit du test je ne l'ai pas ajouté pourtant il est apparu. De plus, j'ai eu des difficultés à réécrire l'histoire des commits, c'est la raison pour laquelle j'ai fait nouvelle pull request #348 au lieu de modifier la #347. 

Je voudrais alors s'il vous plait savoir comment faire pour assigner le fichier  item.jsx au commit feature et comment faire pour modifier la pull request actuelle en prenant en compte les modifications que je vais apporter.

2020-06-08 07:37 UTC, benel commented
> Je voudrais alors s'il vous plait savoir comment faire pour assigner le fichier item.jsx au commit feature et comment faire pour modifier la pull request actuelle en prenant en compte les modifications que je vais apporter.

Comme vos deux commits correspondent à des fichiers bien différents, le plus simple me semble être de : 

1. Faire pointer un branche temporaire sur votre dernier commit (au cas où).
2. Faire descendre votre branche feature-66 de deux commits en arrière (mais sans modifier votre dossier de travail).
3. Reconstituer les deux commits l'un après l'autre.

Je vous propose que vous indiquiez ci-dessous les commandes git que vous pensez devoir faire pour ces étapes et je vous dirai si c'est bon ou s'il faut légèrement les modifier.

2020-06-08 08:51 UTC, JosephNM commented on src/components/itemPage/Item.jsx
> +              </div>
Pour la div vide, je voudrais savoir si je peux la garder ou pas

2020-06-08 08:52 UTC, benel commented on src/components/itemPage/Item.jsx
> +              </div>
Ce n'est pas très "joli", mais si elle est utile, c'est bon.

2020-06-08 09:03 UTC, benel commented on src/components/itemPage/SameNameBlock.jsx
> +    <div className="Item">
> À tort au vu de votre remarque...

C'est surtout qu'il est bizarre de traiter spécifiquement un cas pour afficher quelque chose d'invisible. Soit on le traite et c'est **visible (et cliquable)** soit on ne le traite pas.

>  Mais en lisant le titre je me suis dis que ce cas d'usage ferait l'objet d'un autre ticket.

C'est peut-être **le titre qui n'est pas bon**. De fait l'enjeu est plus dans le passage de l'un à l'autre que ça permet (c'est ce que vous testez d'ailleurs).

> De ce fait si l'item n'a pas de thumbnail, c'est le nom de cet item qui sera affiché 

C'est effectivement une possibilité... 

- L'avantage c'est que l'on comprend que c'est à cause du nom qu'on nous le montre (mais c'est déjà explicite dans le titre de la zone).
- L'inconvénient c'est que s'il y en a plusieurs, ça devient difficile de les distinquer. 

Comme ce deuxième point nous emmène un peu loin, je vous propose d'**utiliser le nom** comme vous le suggériez (si quelqu'un préfère un identifiant, un identicon, ou toute autre solution pour les distinguer, il pourra toujours créer un nouveau ticket).

2020-06-08 11:18 UTC, JosephNM commented
Pour faire descendre la branche de deux commits et refaire proprement les commits, je voudrais faire git reset HEAD~2 --soft (les mêmes faits un autre récit)

2020-06-08 11:55 UTC, JosephNM commented on src/components/itemPage/Item.jsx
> +              </div>
Je compte remplacer cette div par un `hr`

2020-06-08 12:17 UTC, benel commented
> Pour faire descendre la branche de deux commits et refaire proprement les commits, je voudrais faire git reset HEAD~2 --soft (les mêmes faits un autre récit)

Oui, effectivement. Si vous voulez mettre la suite complète de commandes, je pourrai vous la valider.

2020-06-08 13:16 UTC, JosephNM commented
Pour la modification des commits j'ai fait git reset HEAD~2 --soft pour modifier les commits
Ensuite, je fais git status pour voir les fichiers prêts au commit; pour les fichiers de l'implémentation qui étaient ajoutés (item.jsx et app.css) je fais git reset HEAD <file>et je commit la partie test (avec le co-auteur).
Enfin je fais git add pour les autres fichiers de l'implémentation et je commit la partie implémentation. 

Le seul problème maintenant est au niveau du push, car quand je fais git push j'ai une erreur "The current branch feature-66 has no upstream branch". Quand je fais git push --set-upstream origin feature-66 j'obtiens ceci:
 To https://github.com/JosephNM/Porphyry.git
 ! [rejected]        feature-66 -> feature-66 (non-fast-forward)
error: failed to push some refs to 'https://github.com/JosephNM/Porphyry.git'

2020-06-09 08:20 UTC, benel commented
@JosephNM Bravo ! Ça a l'air très bien. Je vais tenter de l'intégrer.

Au sujet de la contribution TEST : votre binôme a contribué au scénario Cucumber ou aux tests Capybara ?

2020-06-09 08:35 UTC, JosephNM commented
Merci @benel !

Pour le test, @SorelMboua  a contribué aux tests capybara. 
Je vais rajouter @hebertquentin et @sbramstein sur la contribution vu que nous avions commencé le scénario cucumber ensemble (je m'excuse pour cet oubli, je pensais que cette contribution concernait uniquement la partie test capybara).

2020-06-09 08:37 UTC, benel commented
C'est noté.

2020-06-09 08:51 UTC, benel commented
@JosephNM Je suis en train de tester votre code. En fait, il y a une exception qui est levée dans les tests existants à la suite de "Soit un item en cours de création".

Vous pouvez le reproduire à la main en ouvrant par exemple http://localhost:3000/item/Vitraux%20-%20Bénel/foo : 

```
Unhandled Rejection (TypeError): undefined is not an object (evaluating 'this.props.item.name.toString')
(anonymous function)
src/components/itemPage/SameNameBlock.jsx:47
```

Il faut protéger l'appel de `toString` au cas où ce qui précède aurait la valeur nulle...

2020-06-09 11:19 UTC, JosephNM commented
Ce que je vais faire c'est générer le bloc des items ayant le même nom si et seulement si la valeur du nom de l'item consulté est non nulle.

2020-06-09 11:37 UTC, JosephNM commented
> Au sujet de la contribution TEST : votre binôme a contribué au scénario Cucumber ou aux tests Capybara ?

Quand vous parlez de scénario cucumber, on est d'accord que cela inclut les propositions que nous avions faites dans le fil de discussion du projet?

2020-06-09 11:59 UTC, benel commented
> Quand vous parlez de scénario cucumber, on est d'accord que cela inclut les propositions que nous avions faites dans le fil de discussion du projet? 

C'est à vous de me dire justement si ces travaux préparatoires se retrouvent (d'une manière ou d'une autre) dans la [version actuelle](https://github.com/Hypertopic/Porphyry/blob/8d0507847d50cd7161f2833f390f6d26c62bbe56/features/check_same_name_items.feature).

2020-06-09 12:56 UTC, JosephNM commented
Je viens de mettre à jour le code de façon à afficher le bloc uniquement si le nom de l'item consulté est non nul. Cependant je ne comprends pas pourquoi le test par Travis crache...

2020-06-09 13:38 UTC, benel commented
> je ne comprends pas pourquoi le test par Travis crache...

Le serveur de test était probablement un peu surchargé. Ça y est c'est passé.

2020-06-09 13:49 UTC, JosephNM commented
D'accord @benel, j'attends vos prochaines remarques.

2020-06-09 14:25 UTC, merged