FEATURE: use in your native language (closes Hypertopic#70)
Hypertopic/Porphyry pull request #350
Opened 2020-06-11 07:31 UTC by garnier5

Co-Authored-By: Ciyax <alexis.heliot21@gmail.com>

## Content

Choose the language according to the browser.
To test, run the `npm run compile` command. 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-11 07:55 UTC, garnier5 commented
Travis ne passe pas.
J'imagine que Travis utilise un navigateur en anglais, ce qui pose des problèmes dans les tests.
J'imagine que les tests devraient être modifié afin de prendre en compte la classe et non pas le texte à l'intérieur du bouton "se connecter...".
@benel

2020-06-11 08:11 UTC, benel commented
> J'imagine que Travis utilise un navigateur en anglais, ce qui pose des problèmes dans les tests.

C'est effectivement probable. 

Vous devez pouvoir changer l'entête `Accept-Language` dans le `features/support/env.rb`.

2020-06-11 08:13 UTC, benel commented
Sur un tout autre sujet (mais relatif à cette PR), notez que depuis peu il y a une nouvelle fonctionnalité et donc un nouveau texte à traduire : 

https://github.com/Hypertopic/Porphyry/blob/v7/src/components/itemPage/SameNameBlock.jsx#L19

2020-06-11 08:34 UTC, garnier5 commented
Cela ne marche pas en modifiant la ligne 11 de env.rb comme cela  : 
`browser_options: { 'no-sandbox': nil, 'Accept-Language': 'fr' },`

2020-06-11 08:37 UTC, garnier5 commented
C'est peu être parce qu'on ne donne pas les bonnes instructions à Travis...
On a essayé d'ajouter des commandes dans la partie script...

2020-06-11 09:00 UTC, garnier5 commented
J'avoue que l'on commence à être à court d'idées...

2020-06-11 09:13 UTC, benel commented
> J'avoue que l'on commence à être à court d'idées...

Regardez ce que vos camarades (je ne sais plus qui) ont écrits pour le test...

2020-06-11 09:19 UTC, benel commented
> Regardez ce que vos camarades (je ne sais plus qui) ont écrit pour le test...

Ici : https://github.com/Hypertopic/Porphyry/issues/70#issuecomment-638728882

Bien entendu, il faut adapter car vous ne pouvez pas partir de `page` mais directement du driver. Mais la fin de la ligne devrait être identique.

2020-06-11 09:24 UTC, garnier5 commented
C'est déjà ce que l'on essaie de faire ensemble (avec @lerideew, le codeur des tests) depuis plus d'une heure mais rien ne marche.

2020-06-11 09:41 UTC, benel commented
> ./src/index.js
Module not found: Can't resolve './locales/en/messages.js' in '/Users/benel/Documents/Formalisations/Code JavaScript/porphyry_v7/src'

Y a-t-il une commande à lancer avant `npm start` ou `npm build` ? Si oui, serait-il possible de l'intégrer aux étapes de production ?

2020-06-11 09:43 UTC, garnier5 commented
Elles sont déjà dans .travis.yml : `npm run extract` et `npm run compile`

2020-06-11 09:47 UTC, benel commented
> C'est déjà ce que l'on essaie de faire ensemble (avec @lerideew, le codeur des tests) depuis plus d'une heure mais rien ne marche.

J'essaie de mon côté...

2020-06-11 09:54 UTC, benel commented
J'ai trouvé :

```ruby
Capybara.current_session.driver.add_headers("Accept-Language" => "fr")
```

2020-06-11 10:00 UTC, garnier5 commented
C'est très étrange...
Le premier scénario passe, mais pas les autres ...

2020-06-11 10:02 UTC, benel commented
> Le premier scénario passe, mais pas les autres ...

Je vais vérifier que ce n'est pas la base de test qui a été cassé par un de vos camarades...

Sinon, c'est que les headers sont remis à zéro à chaque fin de scénario...

2020-06-11 10:14 UTC, benel commented
La base de tests n'est pas cassée. 

Il faut donc trouver la syntaxe pour effectuer une opération automatiquement avant l'exécution de chaque scénario.

2020-06-11 10:18 UTC, benel commented
```ruby
Before do
  Capybara.current_session.driver.add_headers("Accept-Language" => "fr")
end
```

2020-06-11 11:07 UTC, benel commented
Je confirme : les tests passent avec le `Before`.

2020-06-11 12:08 UTC, garnier5 commented
Génial, merci beaucoup !

Je vous envoie mon dernier push avec la correction des tests, et l'ajout de la traduction du texte de nos camarades.

2020-06-11 12:14 UTC, garnier5 commented
Décidément, Travis ne veut pas valider cette nouvelle fonctionnalité...

2020-06-11 12:19 UTC, garnier5 commented
Le serveur de test met beaucoup de temps a charger.
J'imagine que c'est pour cela que Travis refuse les tests.

2020-06-11 13:01 UTC, benel commented
Je pense que certains objets créés par vos camarades génèrent des exceptions dans les vues de CouchDB ce qui génère des pics dans l'utilisation de la mémoire et des logs.

2020-06-11 13:47 UTC, benel commented
@garnier5 Félicitation ! Les tests sont passés !

2020-06-11 13:49 UTC, garnier5 commented
Génial 🎉 !

2020-06-12 07:08 UTC, benel requested changes
@Ciyax @garnier5 

Bravo pour cette belle contribution 🎉 

J'ai une dernière petite demande : 

- [ ] pour éviter d'encombrer le `git status` des développeurs, il faudrait ignorer les fichiers générés par Lingui.js, autrement dit, ajouter à `.gitignore` deux types de `production` : `src/locales/_build` et `src/locales/*/messages.js`.
- [ ] dans le titre de votre commit, je n'ai pas compris la syntaxe de votre référence (`Hypertopic#70`), en général on fait soit une référence à l'entrepôt courant (ex : `#70`) soit à un autre entrepôt (ex : `Acme/Foo#666`). Apparemment ça marche quand même dans ce cas précis, mais ça pourrait ne plus marcher si par exemple les organisations commençaient à avoir elles-mêmes des tickets.

Merci d'avance !

2020-06-12 08:19 UTC, garnier5 commented
Merci beaucoup ! ;)
Je viens de pousser les changements demandés. 
Laissez nous savoir si vous avez besoin d'autres changements.

Aussi, serait-il possible pour vous de cocher toutes les cases dans le ticket associé ?  (#70)

2020-06-12 14:18 UTC, merged