FEATURE: Sort items according to the value of an attribute (closes #38)
Hypertopic/Porphyry pull request #352
Opened 2020-06-11 08:08 UTC by Damien71

Co-Authored-By: UndersCoco corentin.moly@gmail.com

## Content

Allow to sort the items according to the value of a selected attribute.

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-11 08:32 UTC, benel commented
> Co-Authored-By: UndersCoco corentin.moly@gmail.com

Cette syntaxe est à utiliser dans la contributions (`commits`) elle-même. Ex : 97019d547c5732d3e9b22ad83754d5e7505dc1d9

C'est à cette condition que GitHub associera votre binôme au travail réalisé (pour ses stats personnelles, l'icone de son compte dans le commit, etc.).

2020-06-11 09:04 UTC, benel requested changes
Merci beaucoup pour cette contribution.

Comme vous le verrez ci-dessous il y a des petites améliorations à apporter sur le "style" de votre code (nommage, simplification). 

Par ailleurs, j'attire votre attention sur le fait qu'il y a des "conflits" de modification avec les contributions déjà intégrées des autres développeurs. Il faudra que vous les résolviez 

Savez-vous où en sont les tests de votre fonctionnalité ? Seront-ils prochainement livrés ? L'idéal étant bien-sûr que les deux (implémentation et tests) soient livrés en même temps (voire dans la même pull request).

Comme toujours, je suis disponible si vous avez besoin d'aide.

2020-06-11 09:04 UTC, benel commented on src/components/portfolioPage/Corpora.jsx
> +    let attributs = this._getAttributes();
Le code doit être en anglais (`attributes` et non `attributs`).

2020-06-11 09:04 UTC, benel commented on src/components/portfolioPage/Corpora.jsx
> +              onChange={this.props.parentCallback}
Dans le tutoriel React que l'on a fait ensemble il est indiqué : 
> En React, une convention répandue consiste à utiliser des noms on[Event] pour les props qui représentent des événements, et handle[Event] pour les méthodes qui gèrent ces événements.

Il faut trouver un nom d'évènement qui soit suffisamment explicite pour être compréhensible dans les différents composants où le nom va être utilisé. Par exemple : `SortKeyChange` ou plus simplement `Sort`. Ce qui nous donnerait par exemple : 

- `onSort` pour la propriété de `Corpora` plutôt que `parentCallback`,
- `handleSort` pour la fonction qui gère l'évènement plutôt que `callbackFunction`.

2020-06-11 09:04 UTC, benel commented on src/components/portfolioPage/Corpora.jsx
> +              value={this.props.selectedAttribute}
- Le nom `value` est un peu vague pour un ensemble de corpus (d'autant plus qu'il y a une notion appelée `value` dans le modèle mais qui n'a rien à voir).
- Le nom `selectedAttribute` est mal choisi, car dans tout le reste du code et des tests ce que l'on appelle une sélection est en fait un filtre, alors que ce que vous définissez c'est le critère du tri.

Peut-être plutôt : `sortKey` ? `sortCriteria` ? `sortAttribute` ?

2020-06-11 09:04 UTC, benel commented on src/components/portfolioPage/Corpora.jsx
> +    });
C'est un peu dommage de ne pas le faire en approche fonctionnelle (avec notamment [`.filter()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter)). Pouvez-vous essayer ?

2020-06-11 09:04 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +      attribute: "name"
Vous pouvez éviter de toucher à la ligne des `topicsItems` en mettant votre `attribute` à un autre endroit dans la liste.

Notez que ce serait bien là aussi d'avoir un nom qui dise explicitement qu'il s'agit du critère de tri.

2020-06-11 09:04 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        return a["name"][0].localeCompare(b["name"][0]);
Wow ! Ça a l'air bien compliqué pour comparer juste deux chaines de caractère. Je veux bien parier qu'il y a moyen de simplifier tout ça.
Faisons ça avec une approche TDD. Quels sont les cas que vous avez essayé de traiter ?

2020-06-11 09:04 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +  callbackFunction = () => {
Voir plus haut.

2020-06-11 10:04 UTC, Damien71 commented on src/components/portfolioPage/Corpora.jsx
> +              value={this.props.selectedAttribute}
> * Le nom `value` est un peu vague pour un ensemble de corpus (d'autant plus qu'il y a une notion appelée `value` dans le modèle mais qui n'a rien à voir).

value est un attribut du select.

2020-06-11 10:07 UTC, benel commented on src/components/portfolioPage/Corpora.jsx
> +              value={this.props.selectedAttribute}
> value est un attribut du select.

Oui, désolé. Il est difficile d'être totalement concentré sur chaque ligne que m'envoient les étudiants. Mais le reste de mon commentaire reste valable.

2020-06-11 10:10 UTC, Damien71 commented on src/components/portfolioPage/Portfolio.jsx
> +        return a["name"][0].localeCompare(b["name"][0]);
> Wow ! Ça a l'air bien compliqué pour comparer juste deux chaines de caractère. Je veux bien parier qu'il y a moyen de simplifier tout ça.
> Faisons ça avec une approche TDD. Quels sont les cas que vous avez essayé de traiter ?

Les cas traités sont les suivants : 
- L'attribut existe et a une valeur dans les deux items
- L'attribut n'existe pas ou n'a pas de valeur dans le premier item et le deuxième a une valeur 
- L'attribut n'existe pas ou n'a pas de valeur dans le deuxième item et le premier a une valeur
- L'attribut n'existe pas ou n'a pas de valeur dans les deux items

2020-06-17 13:34 UTC, benel commented
Integrated as 4a6dcdcac9e5d6c99e70c85914c157645f493f77. The commit was edited to add your coauthor.

2020-06-17 13:34 UTC, closed without merging