TEST: Consult items on a static geographical map (see #333)
Hypertopic/Porphyry pull request #353
Opened 2020-06-11 10:32 UTC by moonkeys

Co-Authored-By: macchrd <macchrd@users.noreply.github.com>
Co-Authored-By: neumeiej <neumeiej@users.noreply.github.com>

## Content

Acceptance test for #333 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-11 10:47 UTC, macchrd commented
La carte n'est pas générée lorsque nous lançons porphyry en local (npm start). Nous avons conclu que cela était un problème avec `this.props.conf` ce qui empêchait d'avoir les places et donc de générer la map. Nous avons résolu ceci en local en utilisant une clef d'API que nous avions. En ayant cela le test passait. Pensez-vous qu'il se passe quelque chose de similaire avec Travis ?
![image](https://user-images.githubusercontent.com/38346092/84376627-bae85100-abe1-11ea-81c9-2be63458e0c8.png)

2020-06-11 10:55 UTC, benel commented
@macchrd Travis n'a que la configuration qu'on lui donne. Or il est risqué de mettre une clef d'API Google dans le code source.

Je vois deux solutions : 
- soit utiliser les variables d'environnement de Travis (mais ça veut dire modifier la gestion de la configuration dans Porphyry),
- soit mettre suffisamment de contraintes sur les règles d'utilisation de la clef pour éviter que quelqu'un d'autre l'utilise pour un autre usage que les tests.

Je pense que la première est beaucoup plus simple. Je vous invite à regarder dans la console de Google Maps Static ce que l'on pourrait utiliser comme restrictions...

2020-06-11 10:56 UTC, benel commented
Je voulais dire la seconde. Je corrige.

2020-06-15 08:37 UTC, benel commented on features/item_consult_map.feature
> +Alors la carte est affichée
Dans votre scénario, on ne comprend pas très bien à quoi sert cette carte... Son intérêt est qu'elle montre la localisation des items sélectionnés.
L'action (`Quand`) pourrait donc être la sélection d'une catégorie qui du coup change la carte.

Notez que les lieux en question sont accessibles aussi sous forme de textes dans le paramètre `alt` de l'image de la carte.

2020-06-15 08:38 UTC, benel requested changes

2020-06-15 08:38 UTC, benel commented on features/item_consult_map.feature
> +Alors la carte est affichée
Dans votre scénario, on ne comprend pas très bien à quoi sert cette carte... Son intérêt est qu'elle montre la localisation des items sélectionnés.
L'action (`Quand`) pourrait donc être la sélection d'une catégorie qui du coup change la carte.

Notez que les lieux en question sont accessibles aussi sous forme de textes dans le paramètre `alt` de l'image de la carte.

2020-06-30 14:38 UTC, benel commented
> Et "SM 001 n" l'item affiché

Il y a une différence subtile entre "l'item affiché" et un "item affiché". Le premier est dans une page d'item, le second est dans la page du portfolio. C'est pour cela que votre test ne passait pas : vous n'étiez pas dans la bonne page.

À part ça, votre scénario de test est intéressant. Je le mets de côté dans l'attente d'avoir des tests qui puissent utiliser une clef Google sans la divulguer dans les sources.

2020-06-30 14:40 UTC, benel commented
Au fait, qui est l'auteur de quoi  ? 
- @neumeiej du scénario ?
- @macchrd et @moonkeys des étapes de test ?

2020-06-30 14:57 UTC, moonkeys commented
Nous avons écrit la première version du test tous les trois mais @neumeiej a surtout participé au scénario. 
La deuxième version du test a été écrite par @macchrd et moi.

2020-06-30 14:58 UTC, moonkeys commented
> > Et "SM 001 n" l'item affiché
> 
> Il y a une différence subtile entre "l'item affiché" (article défini) et "un item affiché" (article indéfini). Le premier est dans une page d'item, le second est dans la page du portfolio. C'est pour cela que votre test ne passait pas : vous n'étiez pas dans la bonne page.
> 
> À part ça, votre scénario de test est intéressant. Je le mets de côté dans l'attente d'avoir des tests qui puissent utiliser une clef Google sans la divulguer dans les sources.

Merci d'avoir compris notre erreur, nous n'avions pas remarqué cette subtilité dans le code.

2022-06-01 17:09 UTC, closed without merging