FEATURE: Select items according to a given attribute (closes #158)
Hypertopic/Porphyry pull request #355
Opened 2020-06-12 09:02 UTC by Morillev

## Content

Contains modified code to fulfill #158 requirements

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-12 16:32 UTC, benel requested changes
Merci pour votre proposition !

J'ai pas mal de recommandations concernant l'amélioration du code. Comme il s'agit de petites choses mais qui peuvent "casser" votre code. Je vous propose de les prendre une par une (dans l'ordre que vous souhaitez) et de les faire de manière itérative en utilisant Git pour éventuellement revenir à l'étape précédente s'il y a un problème : 

1. Faire une modication.
2. La tester.
3. Si c'est OK ajouter la modification au commit actuel. Sinon, revenir au commit actuel (`git reset  --hard HEAD`).
4. Aller à (1).

2020-06-12 16:32 UTC, benel commented on src/components/InputWithSuggestions.jsx
> -      .sort((x, y) => x.name.localeCompare(y.name));
En supprimant le tri ici, le problème c'est que que du coup dans les autres endroits où `InputWithSuggestions` est utilisé, les candidats ne sont plus triés : 
<img width="1386" alt="Capture d’écran 2020-06-12 à 17 46 35" src="https://user-images.githubusercontent.com/597307/84521415-44c51680-acd5-11ea-80f3-f6eda12baaca.png">
J'ai bien compris pourquoi vous l'avez fait (pour garder toutes les catégories et tous les attributs ensemble), mais du coup voici ce que je vous propose : dans le format des candidats il pourrait y avoir, en plus de `id` et `name` un `type` (qui pourrait être dans votre cas `attribute` et `topic`).
L'idée serait dans `InputWithSuggestions` il y ait un tri à deux niveaux : sur le type et sur le nom.

Il faudra bien entendu vérifier que tout fonctionne bien : 
- dans la barre de recherche,
- et dans l'interface d'ajout de catégories aux items.

2020-06-12 16:32 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +          .map(([key, value]) => key.concat(' : ', value))
Pour la fonction fléchée, Il y a plus court  : 

```js
x => x. concat(' : ')
```

À moins que ce soit pour rappeler au lecteur la structure du tableau généré par `getAttributes` ?

2020-06-12 16:32 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        this.setState({attributes:attributes});
Comme ces attributs sont calculés à partir des items, ce n'est pas forcément une bonne idée de les stocker dans le `state` (ce qui redéclenche le calcul du DOM).

Ce serait plus efficace de faire votre petit traitement en début de `render` et de le "mémoïzer'.

Vous voyez comment on fait ou vous préférez que je le fasse ?

2020-06-12 16:32 UTC, benel commented on src/components/portfolioPage/SearchBar.jsx
> +  candidatesViewpoints = memoize(
Ce serait plus logique d'appeler la variable `topicsCandidates`.

2020-06-12 16:32 UTC, benel commented on src/components/portfolioPage/SearchBar.jsx
> + candidatesItems = memoize(
Ce serait plus logique d'appeler la variable `attributesCandidates`.

2020-06-12 16:32 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +  _getRecursiveItemAttributes(item) {
Changez le nom, ce n'est pas du tout récursif...

2020-06-12 16:32 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +          .map(([key, value]) => key.concat(' : ', value))
Par ailleurs ces trois lignes ressemblent beaucoup à ce que vous aviez appelé `getRecursiveItemAttributes`.
N'y aurait-il pas moyen de factoriser le code ?

2020-06-12 16:32 UTC, benel commented on src/components/portfolioPage/Status.jsx
>    _getTopic(id) {
Comme vous êtes monté en généralité, il faudrait renommer la fonction `_getCandidate` sinon ce n'est pas compréhensible.
On voit par ailleurs au passage que dans Status, `props.viewpoints` et `props.attributes` ne sont utilisés que concaténés. Ça veut dire que vous pourriez utiliser une seul propriété (par exemple `candidates`).

2020-06-12 17:07 UTC, Morillev commented on src/components/InputWithSuggestions.jsx
> -      .sort((x, y) => x.name.localeCompare(y.name));
Pouvons-nous directement modifier le code de getAllPaths() pour ajouter le type ou cela risque de créer des erreurs dans le reste du code?

2020-06-12 17:16 UTC, Morillev commented on src/components/InputWithSuggestions.jsx
> -      .sort((x, y) => x.name.localeCompare(y.name));
Nous avons trouvé une alternative finalement

2020-06-12 18:11 UTC, Morillev commented
J'ai essayé de prendre en compte vos remarque et j'ai modifié notre code, je n'ai juste pas réussi à utiliser memoize et à utiliser votre version raccourcie de la fonction fléchée. J'espère que je n'ai pas fait de bêtises avec github et que vous avez bien les modifications.

2020-06-16 16:52 UTC, benel requested changes
Merci de vos modifications ! 

Je n'ai pas tout revu en détail mais il reste un problème dans votre tri (voir ci-dessous).

2020-06-16 16:52 UTC, benel commented on src/components/InputWithSuggestions.jsx
> +      .sort((x, y) => (x.type === y.type) ? x.name.localeCompare(y.name) : -x.type.localeCompare(y.type))
Dans votre premier cas, il faudrai faire un double tri...

Si on veut simplifier l'algorithme on peut dire aussi que : 

1. on trie d'abord par nom (dans tous les cas),
2. puis, s'il y a un type on trie aussi par type.

2020-06-17 16:11 UTC, benel commented on src/components/InputWithSuggestions.jsx
> -      .sort((x, y) => x.name.localeCompare(y.name));
@Morillev Qui est "nous" ? Avez-vous un co-auteur ?

2020-06-17 16:50 UTC, benel commented on src/components/InputWithSuggestions.jsx
> +      .sort((x, y) => (x.type === y.type) ? x.name.localeCompare(y.name) : -x.type.localeCompare(y.type))
Ah, oui, ça revient au même. J'avais mal lu. Désolé.

2020-06-17 16:52 UTC, benel commented
> Nous avons trouvé une alternative finalement

@Morillev Qui est "nous" ? Aviez-vous un co-auteur ?
Je vais intégrer votre code, ce sera trop tard après pour modifier le commit.

2020-06-17 17:40 UTC, benel commented
Integrated as 70e3919 (to fix indentation).

2020-06-17 17:40 UTC, closed without merging

2020-06-17 19:25 UTC, Morillev commented
@seguragu et moi sommes en binôme, désolé si ce n'était pas clair, nous sommes les auteurs du développement pour ce ticket, nous avons vu que vous aviez intégré notre code, est-ce que cela veut dire qu'on ne doit plus modifier l'algorithme de tri?

2020-06-17 19:31 UTC, benel commented
> @seguragu et moi sommes en binôme, désolé si ce n'était pas clair, nous sommes les auteurs du développement pour ce ticket

Ah, c'est dommage : c'est trop tard pour le mentionner dans le commit. 
Mais bien entendu, je le note pour dans mon tableau des compétences pour IF05.

> est-ce que cela veut dire qu'on ne doit plus modifier l'algorithme de tri?

Non, pas besoin. Comme je l'ai écrit plus haut, je l'avais mal lu. En fait il était bon. 

Félicitation à vous deux @seguragu et @Morillev 🎉