REFACTORING: Checking changes before reloading portfolio (closes #354)
Hypertopic/Porphyry pull request #356
Opened 2020-06-12 09:15 UTC by garnier5

## Content

Checking for changes before reloading the portfolio

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-15 08:57 UTC, benel requested changes
Merci beaucoup pour cette contribution !

À corriger : quelques petites entorses aux règles de style `eslint` du projet.

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +      return fetch(SERVICE)
Quand la définition de votre fonction fléchée se limite à un `return` vous pouvez simplifier l'écriture : 

```js
() => {
  return A;
}
```

devient : 

```js
() => A
```

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        let end=new Date().getTime();
Les règles d'`eslint` du projet demandent qu'il y ait un espace entre les opérateurs infixés (comme ici l'affectation).

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        let elapsedTime=end-start;
Idem.

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        console.log("elapsed Time ",elapsedTime);
Les règles d'`eslint` du projet demandent : 
- qu'il y ait un espace après les virgules,
- les "quotes" soient préférées aux guillemets.

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        let intervalTime=Math.max(10000,elapsedTime*5);
Les règles d'eslint du projet demandent :
- un espace entre les opérateurs infixés (comme ici l'affectation),
- qu'il y ait un espace après les virgules.

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        console.log("reload every ",intervalTime);
Les règles d'`eslint` du projet demandent :

- qu'il y ait un espace après les virgules,
- les "quotes" soient préférées aux guillemets.

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +            .then(response => response.json())
Les règles d'eslint du projet demandent qu'il y ait une indentation quand on commence une ligne par un point.

2020-06-15 08:57 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +
Merci de supprimer la ligne vide. Je trouve que ça "casse" la perception du bloc.

2020-06-15 11:19 UTC, garnier5 commented on src/components/portfolioPage/Portfolio.jsx
> +        let end=new Date().getTime();
D'accord, je pensais que je ne devais pas corriger le code qui n'est pas le mien ;)

2020-06-15 11:22 UTC, garnier5 commented on src/components/portfolioPage/Portfolio.jsx
> +        console.log("elapsed Time ",elapsedTime);
Les simples quotes, ou les doubles quotes ?

2020-06-15 11:25 UTC, garnier5 commented
Corrigé

2020-06-15 11:35 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +        let end=new Date().getTime();
Il apparaît en vert. Donc il a été marqué comme modifié par vous (probablement à cause de l'indentation)...

2020-06-15 11:38 UTC, garnier5 commented on src/components/portfolioPage/Portfolio.jsx
> +      return fetch(SERVICE)
Je n'avais pas vu celui là, je corrige rapidement et je push

2020-06-15 11:41 UTC, garnier5 commented on src/components/portfolioPage/Portfolio.jsx
> +      return fetch(SERVICE)
Cette fois-ci, c'est réellement corrigé

2020-06-15 12:11 UTC, benel requested changes
Merci pour toutes ces modifications.

Une dernière petite interrogation concernant un bloc (`new Promise`) dont je ne comprends pas l'intérêt...
mais peut-être a-t-il une raison d'être...

2020-06-15 12:11 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> +    );
Pourquoi pas tout simplement : 

```js
    let SERVICE = (await conf).services[0];
    return fetch(SERVICE)
       .then(response => response.json())
       .then(data => {
         this.update_seq = data.update_seq;
       })
     );
```
?

2020-06-15 17:44 UTC, garnier5 commented on src/components/portfolioPage/Portfolio.jsx
> +    );
C'est vrai que c'est beaucoup plus simple !

2020-06-16 09:35 UTC, merged

2020-06-16 09:37 UTC, benel commented
Merci pour cette contribution @garnier5 🎉