Test: Sort items according to the value of an attribute (see #38)
Hypertopic/Porphyry pull request #357
Opened 2020-06-14 09:24 UTC by HONGXinY

Co-authored-by: CHEN Yiyi <yiyi.chen@utt.fr>

## Content

Test of function: Sort items according to the value of an attribute

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-15 08:44 UTC, benel requested changes
Merci pour cette contribution.

Voici quelques premiers commentaires pour améliorer votre test.

2020-06-15 08:44 UTC, benel commented on features/if05_38.feature
> +Et "SR 005" un des items affichés
Ce serait encore mieux si vous indiquiez ici aussi l'ordre dans lequel ils sont **avant** le changement de critère de tri.

2020-06-15 08:44 UTC, benel commented on features/if05_38.feature
> +Et "Datation" une des rubriques développées
Inutile

2020-06-15 08:44 UTC, benel commented on features/if05_38.feature
> +Et on sélectionne la rubrique "XIXe s."
Utile seulement s'il vient remplace le premier `Soit` (pour que le test soit plus rapide).

2020-06-15 08:44 UTC, benel commented on features/step_definitions/outcome.rb
> +end
Astucieux !

Attention à l'indentation de votre code.

2020-06-15 08:44 UTC, benel commented on features/if05_38.feature
> +|Items|
Pourquoi `Items` ?

2020-06-15 08:44 UTC, benel commented on features/if05_38.feature
> +Quand on sélectionne le sélecteur "Semestre"
`Semestre` ?!? C'est quoi le semestre d'un vitrail ? ;)

2020-06-16 14:11 UTC, HONGXinY commented
Merci de vos prpositions ! C'est corrigé.

2020-06-16 16:48 UTC, benel requested changes
@HONGXinY Vous n'avez compris mon conseil... [Comme @yiyi1998 l'avait fait pour les UE](https://github.com/Hypertopic/Porphyry/issues/38#issuecomment-638662871), vous devez avoir **deux listes ordonnées** (différemment) **avant** (dans le `Soit`) et **après** (dans le `Alors`) le changement du critère de tri.

Par exemple : 

- triés par nom : `SM 008g` est avant `SNZ 006`,
- triés par date de prise de vue (`created`) : `SNZ 006` (`2014-04-05`) est avant `SM 008g` (`2016-03-13`).

2020-06-18 22:10 UTC, garnier5 commented
@HONGXinY @yiyi1998 
Que pensez-vous d'un test comme cela, avec deux listes, pour voir la différence avant/après ?

portfolio_sort.feature

```
Fonctionnalité: Trier les items du portfolio

Scénario: Par la valeur de l'attribut spatial
Soit "vitraux" le portfolio ouvert
Et "Datation" une des rubriques développées
Et on sélectionne la rubrique "XIXe s."
Et je vois la liste comme ci-dessous
|SM 001 m|
|SM 001 n|
|SR 005|
Quand on sélectionne le sélecteur "spatial"
Alors je vois en ordre la liste
|SR 005|
|SM 001 m|
|SM 001 n|
```

2020-06-19 05:48 UTC, benel commented
@garnier5 

C'est tout à fait l'idée !

@HONGXinY @yiyi1998

Quelques pistes d'amélioration : 
- [ ] ouvrir directement le portfolio avec la sélection XIXe (pour un test plus rapide, surtout que come c'est un test qui ne modifie pas les données on pourrait avoir envie aussi de le lancer sur le site de production),
- [ ] formuler les étapes avec `l'utilisateur` plutôt que `on` par cohérence avec les étapes existantes.
- [ ] formuler les deux étapes avec les listes de manière analogue, sans forcément impliquer l'utilisateur (qui `voit`), met en mettant l'accent sur le fait que ce sont des `items` et qu'ils sont `dans cet ordre`.
- [ ] reformuler `sélectionne le sélecteur` en utilisant l'action de haut niveau décrite par le titre de la fonctionnalité.

2020-06-19 05:55 UTC, benel commented
@garnier5 
@HONGXinY @yiyi1998

Par ailleurs, il faudrait trouver des exemples qui fonctionnent.

2020-06-30 13:28 UTC, benel commented
Integrated as 55458c8.

2020-06-30 13:28 UTC, closed without merging