TEST: Get similar items according to an item's attribute value (see #39)
Hypertopic/Porphyry pull request #359
Opened 2020-06-15 18:09 UTC by jejroux

## Content

Ecriture des "acceptance tests".

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2020-06-16 08:29 UTC, benel requested changes
Merci de cette contribution. C'est effectivement ce qui manquait à la pull request #340 de  @melaniehoneychurch. 

En plus des commentaires dans le code, pourriez-vous s'il vous plaît fusionner les deux commits (celui de @melaniehoneychurch et le vôtre), en indiquant vos deux noms comme co-auteurs ?

Merci d'avance.

2020-06-16 08:29 UTC, benel commented on features/step_definitions/event.rb
> +    click_on class: 'ValidateButton'
Merci d'enlever de votre commit cette ligne, puisqu'elle n'a pas de rapport avec votre commit.

2020-06-16 08:29 UTC, benel commented on features/step_definitions/event.rb
> +Quand("on choisit l'attribut {string}") do |attribute|
Comme cette étape ne peut pas encore fonctionner (puisque la fonctionnalité n'est pas encore implémentée), ajoutez la ligne : 
```ruby
  pending "To be implemented"
```

2020-06-17 12:21 UTC, jejroux commented on features/step_definitions/event.rb
> +Quand("on choisit l'attribut {string}") do |attribute|
> En plus des commentaires dans le code...

@benel De quels commentaires parlez-vous ?

2020-06-17 12:25 UTC, benel commented on features/step_definitions/event.rb
> +Quand("on choisit l'attribut {string}") do |attribute|
Ben celui-ci par exemple sur le `pending` ou bien le précédent sur la ligne qui n'a pas de rapport avec le `commit` thématique.

2020-06-18 09:01 UTC, jejroux commented
@benel, j'ai voulu faire les changements demandés et corriger mon commit précédent mais je pense qu'il y a un soucis puisque bash me répond ceci après mon commit --amend :
`[test-39 d8a3880] TEST: Get similar items according to an item's attribute value (see #39)
 Author: Aurelien Benel <aurelien.benel@utt.fr>
 Date: Mon Jun 15 09:53:55 2020 +0200
 4 files changed, 20 insertions(+), 11 deletions(-)`

Je n'ose donc pas push ma branche de peur de modifier des choses que vous auriez faites...

2020-06-18 09:07 UTC, benel commented
Je ne comprends pas le message et non, je n'ai pas modifié votre commit. 

Comme je le disais dans mes différents messages depuis ce matin. On pourra reparler de vos tests **une fois que** votre vidéo sera terminée et déposée.

2020-06-30 14:27 UTC, benel commented
@jejroux Vos étapes de test ainsi que le scénario (de @melaniehoneychurch) viennent d'être intégrés. Je vous invite à regarder comment les deux s'articulent pour constituer un test qui fonctionne : c6b071a.

2020-06-30 14:27 UTC, closed without merging

2020-07-02 17:58 UTC, jejroux commented
Merci ! Tout est clair !