TEST: Search for an attribute and select a value
Hypertopic/Porphyry pull request #437
Opened 2021-04-16 07:53 UTC by JacquesMironneau

Adding a "Search by attribute type" test in the feature "Select items by searching"

2021-04-21 14:45 UTC, benel requested changes
Vous êtes sur la bonne voie pour le scénario (il reste quelques petits problèmes que j'ai pointés directement dans le code).

L'historique est parfait. Bravo !

2021-04-21 14:45 UTC, benel commented on features/portfolio_search.feature
> +  Alors l'item "PSM 002" est affiché
Le test n'est pas suffisant pour vérifier que la situation finale est différente de la situation initiale.

2021-04-23 10:05 UTC, JacquesMironneau commented
J'ai ajouté les éléments qui doivent être cachés dans le test

2021-06-28 17:00 UTC, benel commented on features/portfolio_search.feature
> +  Alors l'item "PSM 002" est affiché
Pour montrer le comportement d'une fonctionnalité, c"est bien aussi de préciser la situation initiale.

2021-06-28 17:02 UTC, closed without merging