FEATURE: search for attribute with item value
Hypertopic/Porphyry pull request #440
Opened 2021-04-16 08:15 UTC by JacquesMironneau

Search for a topic and select it (see #154)

2021-04-21 14:53 UTC, benel requested changes
Vous êtes sur la bonne voie pour le scénario (il reste quelques petits problèmes que j'ai pointés directement dans le code).

Votre historique est propre (bravo !), par contre l'intitulé n'est pas très clair. Pourquoi ne pas dire que l'on cherche l'attribut et que l'on choisit sa valeur ?

2021-04-21 14:53 UTC, benel commented on features/portfolio_search.feature
> +  Alors l'item "SM 001 n" est affiché
Le test n'est pas suffisant pour vérifier que la situation finale est différente de la situation initiale.

2021-04-23 09:31 UTC, JacquesMironneau commented
J'ai modifié le code ainsi que le nom pour que cela soit plus clair

2021-06-28 16:51 UTC, benel commented
OK.

2021-06-28 16:51 UTC, closed without merging