TEST: Scenarios - Authorize a contributor to edit a viewpoint (see #183)
Hypertopic/Porphyry pull request #503
Opened 2021-05-17 15:02 UTC by candalc

## Content

Scenarios (Gherkin) which illustrate the feature "Authorize a contributor to edit a viewpoint" (ticket  #183) done with 
 @Samnoel95. Since the ticket corresponds to a new feature, we put the scenarios in a new file named `viewpoint_authorize_editing.feature`, according to the other scenarios files in the `features` folder.

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [ x be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2021-05-17 16:59 UTC, benel commented
Merci pour ce scénario @candalc @Samnoel95.

Vous avez une erreur à la ligne 33:

> features/viewpoint_authorize_editing.feature: (33:1): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ExamplesLine, #ScenarioLine, #RuleLine, #Comment, #Empty, got 'Fonctionnalité: Ajouter un contributeur à la liste d'édition d'un point de vue' (Cucumber::Core::Gherkin::ParseError)

Comme l'indique le message, cucumber ne s'attendait pas à trouver `Fonctionnalité` à cette ligne. C'est parce que normalement, il n'y en a qu'une par fichier.

2021-05-20 06:32 UTC, benel requested changes
Vous avez dû voir que vos tests échouent sur `Soit l'utilisateur est connecté`.
C'est parce qu'on ne peut être connecté que si on a ouvert une page préalablement.
Dit autrement, cherchez dans https://github.com/Hypertopic/Porphyry/blob/v7/features/step_definitions/context.rb une étape contenant `visit` et qui pourrait être appliquée à votre scénario.

2021-05-21 06:29 UTC, benel requested changes
Merci @candalc @Samnoel95 pour cette nouvelle version. 

Maintenant que la forme est bonne, améliorons le fond.

La liste de vos cas est plutôt pas mal (à quelques exceptions près). Par contre, leur description reste un peu confuse parce que vous ne distinguez pas clairement les deux utilisateurs dans la phrase pivot  "Quand A autorise B à éditer le point de vue X".

Par ailleurs, ne vous appuyez pas sur le fait que l'interface présente ou cache une fonctionnalité : 
-  d'abord parce que ce n'est pas assez sûr (il est très facile pour n'importe quel utilisateur informaticien de le contourner).
- ensuite parce que ce n'est pas cohérent avec les choix faits jusqu'alors dans l'interface de l'application (à la manière des sites participatifs, on montre tout ce que l'on peut faire dans l'interface, même quand on y est pas autorisé, de sorte que les usagers aient une idée complète des possibilités et qu'il ait envie d'être autorisés à le faire).

Je vous conseille donc : 
- de décrire en français l'ensemble des cas pour `A`, `B` et `X`, 
- de vérifier que vous avez l'histoire complète pour montrer ce qui se passe, autrement dit pour voir ce qui change (ou pas) entre la situation initiale (avant le QUAND) et la situation finale (après le QUAND).

N'hésitez pas à me montrer des versions même non abouties pour un feedback plus rapide.

2021-05-24 08:55 UTC, candalc commented
> Je vous conseille donc :
> 
> * de décrire en français l'ensemble des cas pour `A`, `B` et `X`,
> * de vérifier que vous avez l'histoire complète pour montrer ce qui se passe, autrement dit pour voir ce qui change (ou pas) entre la situation initiale (avant le QUAND) et la situation finale (après le QUAND).

Après réécriture des scénarios, on aboutit à la version suivante des scénarios écrits en français. Pour vérifier que l'utilisateur peut bien modifier un point de vue, on s'appuie sur le fait que le bouton cliquable de modification d'un point de vue redirige vers la page avec l'url qui se termine par `.../viewpoint/id_viewpoint`. On aurait donc :

**Scénario : L'utilisateur est noté sur la liste d'édition du point de vue**

- Si l’utilisateur {A} est connecté, et le portfolio {P} est ouvert, et l’utilisateur {A} est noté sur la liste d’édition du point de vue {X} du portfolio {P}, et que l’utilisateur {A} clique sur "Modifier le point de vue {X}", alors l’utilisateur {A} accède à la page '_{P}.porphyry.org/viewpoint/{id_de_X}_'

**Scénario : Le contributeur est l'auteur d'un point de vue**

- Si l’utilisateur {A} est l’auteur du point de vue {X}, et la liste d’édition du point de vue {X} existe, alors l’utilisateur {A} est noté sur la liste d’édition du point de vue {X}

**Scénario : La liste d'édition du point de vue n'est pas définie**

- Si le portfolio {P} est ouvert, et l’utilisateur {A} est connecté, et la liste d’édition du point de vue {X} n’existe pas, et que l’utilisateur {A} clique sur "Modifier le point de vue {X}", alors l’utilisateur {A} reste sur la page '_{P}.porphyry.org_'

**Scénario : L'utilisateur n'est pas noté sur la liste d'édition du point de vue**

- Si le portfolio {P} est ouvert, et l’utilisateur {A} est connecté, et l’utilisateur {A} n’est pas noté sur la liste d’édition du point de vue {X}, et que l’utilisateur {A} clique sur "Modifier le point de vue {X}", alors l’utilisateur {A} reste sur la page '_{P}.porphyry.org_'

**Scénario : L'utilisateur n'est pas connecté**

- Si l’utilisateur {A} n’est pas connecté, et que l’utilisateur {A} clique sur "Modifier le point de vue {X}", alors l’utilisateur {A} reste sur la page '_{P}.porphyry.org_'

**Scénario : L'utilisateur ajoute un contributeur à la liste d'édition**

- Si le portfolio {P} est ouvert, et l’utilisateur {A} est connecté, et l’utilisateur {A} est noté sur la liste d’édition du point de vue {X}, et l’utilisateur {B} n’est pas noté sur la liste d’édition du point de vue {B}, alors quand l’utilisateur {A} ajoute l’utilisateur {B} sur la liste d’édition du point de vue {X}, l’utilisateur {A} et l’utilisateur {B} sont notés sur la liste d’édition du point de vue {X}

Que pensez-vous de cette ébauche de scénarios @benel ?

2021-05-24 09:17 UTC, benel commented
Merci @candalc pour cette nouvelle version de vos scénarios. 
Quand je disais "en français", c'était pour éviter le caractère un peu formel de Cucumber : c'était pour réduire un peu la difficulté de faire un scénario parfait dès le début... Mais bon, ce n'est pas grave. Si ça vous va ainsi...

> Après réécriture des scénarios, on aboutit à la version suivante des scénarios écrits en français. Pour vérifier que l'utilisateur peut bien modifier un point de vue, on s'appuie sur le fait que le bouton cliquable de modification d'un point de vue redirige vers la page avec l'url qui se termine par .../viewpoint/id_viewpoint. On aurait donc :

Ce n'est pas le choix qui a été fait jusqu'à maintenant dans l"interface de Porphyry : on peut essayer de tout faire (même sans être connecté). C'est juste que ça n'aura aucun effet. Autrement dit, on a privilégié l'exploration de l'interface au profit de la certitude que l'on n'est pas en train de perdre son temps. Comme tout choix de conception, il est discutable. Cependant, si on choisissait de faire un autre choix aujourd'hui, il faudrait appliquer ce nouveau choix sur l'ensemble de l'application.

L'intérêt pour vous du choix de conception qui a été fait c'est que cela rend plus facile la description du comportement : 

```cucumber
  Soit "Truc" un truc dont les contributeurs sont "alice|charly"
  Et "bob" l'utilisateur connecté
  Quand l'utilisateur machine "Truc"
  Alors "Truc" n'est pas machiné
```

Je vous laisser reformuler vos scénarios ainsi (et cette fois-ci avec des noms d'utilisateur et de points de vue).

> Scénario : L'utilisateur n'est pas connecté

Inutile d'écrire ce scénaro. Ceci est un problème d'authentification et non d'autorisation. C'est déjà géré.

2021-05-26 13:04 UTC, benel requested changes
Félicitations @candalc ! 🎉 
Ce n'était pas évident et vous vous en êtes très bien sortie !

Il y a des toutes petites choses qui pourraient être améliorées (notamment sur la première étape de chaque scénario soit pour que le test soit plus rapide soit pour qu'il n'échoue pas), mais ça peut tout à fait attendre le livrable des tests.

Pour être intégrée à la branche principale, il ne vous manque plus qu'à faire une petite réécriture de l'historique avec Git : 
- [ ] un seul commit,
- [ ] dont le titre commence par `SCENARIO` (pour éviter d'attendre d'avoir les tests), 
- [ ] avec ensuite le nom de la fonctionnalité,
- [ ] et la référence au ticket sous la forme `(see #xxx)`,
- [ ] en utilisant la [syntaxe spécifique à GitHub pour mentionner les co-auteurs](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) s'il y en a.

2021-05-26 17:06 UTC, benel approved these changes

2021-05-26 17:07 UTC, merged