TEST: Add Gherkin scenario related to custom geocoding feature (see #349)
Hypertopic/Porphyry pull request #504
Opened 2021-05-17 17:01 UTC by florian-dehe

## Content

This pull request adds a gherkin scenario for the issue #349. It also adds empty pending Capybara implementations of new Gherkin scenario rules.

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2021-05-20 06:16 UTC, benel requested changes
Merci pour cette contribution. Elle est très intéressante.

Quelques points d'amélioration ou d'interrogation : 

- à propos de l'historique 
  - essayez de regrouper ceci en une ou deux contributions (une par scénario),
  - comme préfixe – c'est vrai que ce n'était pas (encore) dans les règles – mais comme les livrables Gherkin et Capybara sont individualisés, je pense que `SCENARIO` serait préférable,
  - une fois qu'il y aura le bon préfixe, vous pourrez le faire suivre par un vrai titre de fonctionnalité (action de l'utilisateur) sans qu'il y ait d'ambiguité,
  -  ce n'est peut-être pas nécessaire d'inclure les "patrons" pour Capybara (sauf erreur de ma part, les undefined ne causent pas d'erreur, si ?), 
- à propos des cas
    - c'est un peu paradoxal que vous parliez de "custom geocoded" et que votre cas soit celui d'une adresse connue de GoogleMaps, il faudrait probablement avoir deux scénarios : un pour chaque cas,
    - vous avez adapté la fonctionnalité au corpus de test, ce qui est plutôt bien dans la perspective des tests, mais peut-être un peu tôt, car autant on voit bien les deux cas pour Kerameikos, autant c'est plus difficile de voir ce que ça pourrait donner pour les vitraux (peut-être d'ailleurs que ça nécessiterait d'ailleurs un second jeu de tes).
    - le binôme qui travaille sur les tests verra, mais il est possible que ce soit assez difficile de le tester sur l"interface : une alternative serait de faire un test d'API (donc plus bas niveau, dans GeoXEne et non dans Porphyry), en reprenant les fameux deux cas (un cas connu de GoogleMaps et un défini dans GeoXEne).

2021-05-20 06:23 UTC, benel commented
Et n'oubliez pas, si vous l'avez fait en binôme, d'indiquer le co-auteur dans le commit : https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

2021-05-28 08:23 UTC, florian-dehe commented
Les changements demandés dans les commentaires précédents ont été appliqués et la PR a été renommée de ce fait.

2021-05-28 08:26 UTC, florian-dehe commented
Les tests ne sont pas passés car il faudrait ajouter une nouvelle entrée dans les données de tests avec un attribut "spatial" inconnu de Google Maps et que l'on pourrait tester avec GeoXEne.

2021-05-28 09:26 UTC, benel commented
@florian-dehe @franckfotso1 @ClemUTT Vous êtes trois dans votre binôme ?

> Les tests ne sont pas passés car il faudrait ajouter une nouvelle entrée dans les données de tests avec un attribut "spatial" inconnu de Google Maps et que l'on pourrait tester avec GeoXEne.

Ce n'est pas ce que disent les logs de Cucumber : les tests échouent dès cette étape-ci : 

```cucumber
Et le titre de l'item affiché est "AXY 001"
```

C'est tout simplement parce que ce vitrail n'existe pas dans la base de tests.


```cucumber
Et la valeur de l'attribut "spatial" est "Inconnu"
```

C'est "Inconnu" la valeur de spatial ???

Votre but n'est-il pas de montrer que GeoXEne sait répondre là où GoogleMaps ne savait pas répondre. Pourquoi ne pas prendre [une des valeurs que connaît GeoXEne](https://github.com/Hypertopic/GeoXEne/blob/main/src/server.js#L8-L27) ? 

On peut toujours réfléchir en parallèle à un exemple plus adapté au domaine des vitraux et de l'ajouter à GeoXEne. Mais en attendant ces valeurs nous permettront de tester la fonctionnalité.

2021-05-28 11:19 UTC, florian-dehe commented
> @florian-dehe @franckfotso1 @ClemUTT Vous êtes trois dans votre binôme ?

Nous sommes trois, sinon quelqu'un serait tout seul et il me semble que vous preferez que personne ne soit seul pour un livrable.

 
> C'est tout simplement parce que ce vitrail n'existe pas dans le [jeu de test](https://github.com/Hypertopic/Argos/tree/v4/__tests__/api/fixtures).

Nous avons pensé à rajouter une nouvel élément dans les données de tests d'Argos qui aurait un attribut spatial spécifique pour GeoXEne. Le nom n'était surement pas assez explicite.


> Votre but n'est-il pas de montrer que GeoXEne sait répondre là où GoogleMaps ne savait pas répondre. Pourquoi ne pas prendre [une des valeurs que connaît GeoXEne](https://github.com/Hypertopic/GeoXEne/blob/main/src/server.js#L8-L27) ?

Nous allons prendre en compte cela et modifier cette partie.

 
> On peut toujours réfléchir en parallèle à un exemple plus adapté au domaine des vitraux et de l'ajouter à GeoXEne. Mais en attendant ces valeurs nous permettront de tester la fonctionnalité.

C'est exactement à quoi nous pensions (voir plus haut dans la réponse).

2021-05-28 15:09 UTC, florian-dehe commented
J'ai créé une nouvelle entrée dans Capybara pour mettre une ligne de scénraio en pending.
Les tests sont passés.

@benel Je considère le livrable fini pour moi.

2021-05-28 15:46 UTC, benel commented
@florian-dehe 

Une idée pour votre scénario : ce qui est marqué ["Abbaye Saint-Loup"](https://vitraux.porphyry.org/?t={%22type%22:%22intersection%22,%22data%22:[{%22type%22:%22intersection%22,%22selection%22:[%22spatial%20:%20Abbaye%20Saint-Loup,%20Troyes%22],%22exclusion%22:[]}]}) est mal positionné. Ce qui apparaît est l'adresse postale (dans une arrière cour) mais pas la position réelle, ce qui est assez embêtant quand on est un visiteur...

<img width="480" alt="Capture d’écran 2021-05-28 à 17 44 43" src="https://user-images.githubusercontent.com/597307/120009661-7dd8c280-bfdc-11eb-9fca-efc0bbdf0feb.png">

2021-05-28 15:53 UTC, florian-dehe commented
@benel 

Très bonne idée ! Je vais regarder ca dans les jours qui viennent.

2021-05-31 07:14 UTC, florian-dehe commented
L'item référencé dans le commit n'est pas dans les données de test Argos mais uniquement dans la version de production.

2021-05-31 12:08 UTC, benel commented
@florian-dehe 

> L'item référencé dans le commit n'est pas dans les données de test Argos mais uniquement dans la version de production.

OK. En voici un ajouté au jeu de test : https://github.com/Hypertopic/Argos/commit/4e873abf192b46bae8fe4050ae9eb640f9f957ce

Ne sachant pas très bien quel panneau de la fenêtre vous vouliez, j'ai pris volontairement, dans une autre fenêtre du même endroit,  un vitrail avec un sujet très différent des sujets habituels...

Notez bien que j'en ai profité pour être plus précis dans le lieu ("Société académique de l'Aube" au lieu de "Abbaye Saint-Loup": du coup, le préfixe du nom de l'item a également changé ("SAA" au lieu de "SLP").

2021-05-31 12:26 UTC, florian-dehe commented
Je voulais tester dans la fenêtre spécifique à un item car (il me semble) que c'est le seul moyen d'accéder à l'attribut spatial ?

Pour le reste, ce n'est qu'un appel de l'API GeoXEne donc pas de tests visuels.

2021-05-31 15:47 UTC, benel commented
@florian-dehe 

> Je voulais tester dans la fenêtre spécifique à un item car (il me semble) que c'est le seul moyen d'accéder à l'attribut spatial ?

Heu, oui... Je ne crois pas avoir dit le contraire... Si ?

Mon message concernait juste le fait que les données de votre scénario doivent être très légèrement modifiées (nom et lieu) pour correspondre à l'item que j'ai ajouté dans les tests.

> Pour le reste, ce n'est qu'un appel de l'API GeoXEne donc pas de tests visuels.

On parle toujours du scénario ? 
Pour l'instant, vous n'avez pas vraiment à vous demander comment ça va être testé.
Notez que vous n'êtes pas obligé de mettre les signatures des fonctions. Du moment qu'elles sont indéfinies, elles seront en "jaune" (comme vos fonctions en mode "pending") et non en "rouge".

Le binôme qui travaillera sur les tests pourra considérer trois solutions : 
- soit une solution un peu détournée pour évaluer de manière non visuelle la dernière étape (par exemple grâce à un mode textuel pour les mal-voyants),
- soit un test d'API pour GeoXEne, mais du coup on ne teste pas le code apporté à Porphyry, ce qui est un peu dommage,
- soit un test manuel, mais du coup il faudra écrire chaque étape (notamment le test visuel pour dire ce qui est acceptable et ce qui ne l'est pas).

2021-05-31 16:09 UTC, florian-dehe commented
@benel 
OK. Faut-il que j'enlève les signatures Capybara ?

2021-05-31 16:23 UTC, benel commented
> OK. Faut-il que j'enlève les signatures Capybara ?

Ce serait mieux, oui.

2021-05-31 16:24 UTC, benel commented
> OK. Faut-il que j'enlève les signatures Capybara ?

Ce serait mieux, oui. @florian-dehe

2021-06-01 06:33 UTC, florian-dehe commented
@benel Tout est bon

2021-06-02 12:21 UTC, benel requested changes
Super @florian-dehe @franckfotso1 @ClemUTT !

Une dernière petite modification et j'intègre votre contribution !

2021-06-02 12:21 UTC, benel commented on features/portfolio_map.feature
> +Scénario: Requête latitude and longitude connu de Google Maps
Petit problème d'accord du participe passé "connu".

Je vous propose de profiter de l'amendement pour simplifier le nom du scénario en `connue de Google Maps`. En effet lors du lancement de cucumber en mode "brief", le titre de la fonctionnalité et ceux des scénarios sont affichés à la suite, de la manière suivante : 

```
Voir les items placés sur la carte pour toute localisation
- connue de Google Maps ✅ 
- connue seulement de GeoXEne ✅
```

2021-06-02 12:21 UTC, benel commented on features/portfolio_map.feature
> +Scénario: Requête latitude and longitude connu seulement de GeoXene
- Idem. Voir plus haut.
- Attention, dans GeoXEne le "E" est aussi en majuscule (pour "emulation").

2021-06-02 12:23 UTC, benel commented
Et je précise que j'ai vérifié les coordonnées... et ce sont les bonnes 👏🏼

2021-06-02 14:04 UTC, florian-dehe commented
@benel  Les changemensts ont étés appliqués

2021-06-02 16:06 UTC, merged

2021-06-02 16:07 UTC, benel commented
Félicitations ! Votre scénario est intégré !

2021-06-02 16:08 UTC, benel commented
Félicitations @florian-dehe @franckfotso1 @ClemUTT ! 🎉 
Votre scénario est intégré !