TEST: Scenarios - Create bidirectional link (see Hypertopic#188)
Hypertopic/Porphyry pull request #507
Opened 2021-05-20 09:05 UTC by ThomasRitaine

### Description

Scenarios which illustrate the feature "Create bidirectional link" (ticket #188) done with @xelocks .
Since the ticket corresponds to a new feature, we put the scenarios in a new file named create_bidirectional_link.feature, according to the other scenarios files in the features folder.

### Content

Scénario pour la création de liens bidirectionnels entre deux items comme des UEs.

2021-05-26 07:57 UTC, benel requested changes
Merci pour cette première version du scénario.

Vous trouverez dans mes commentaires ligne à ligne des pistes pour l'améliorer.

2021-05-26 07:57 UTC, benel commented on features/create_bidirectional_link.feature
> +Fonctionnalité : Avoir un lien bidirectionnel entre les items
Il y a une incohérence entre le verbe de la fonctionnalité utilisé dans le ticket et celui utilisé dans vos scénarios. Je vous rappelle que le verbe désigne toujours une action de l'utilisateur.
S'il s'agit de "créer un lien bidirectionnel" : on doit avoir une situation initiale dans laquelle on ne l'a pas encore et une situation finale dans laquelle on l'a.

2021-05-26 07:57 UTC, benel commented on features/create_bidirectional_link.feature
> +Scénario : L’utilisateur souhaite visualiser les prérequis d’une UE
Le nom des scénarios doit rester générique (indépendant du domaine).

2021-05-26 07:57 UTC, benel commented on features/create_bidirectional_link.feature
> +  Alors une des rubriques de l’item est “Prérequis”
Maladroit ("rubrique" étant une des traductions officielles de "topic").

2021-05-26 07:57 UTC, benel commented on features/create_bidirectional_link.feature
> +  Et la page contient “NF04”
Il faudrait arriver à mettre dans la même étape "pré-requis" et "NF04".
Après tout, c'est ensemble que ça prend tout son sens et non séparément.

2021-05-26 07:57 UTC, benel commented on features/create_bidirectional_link.feature
> +  Alors une des rubriques de l’item est “Approfondissements”
Si vous êtes obligés à chaque fois que vous créez un lien birectionnel de donner les noms de la relation dans les deux sens, ça va être un peu lourd... 
Je ne sais pas ce que vous propose l'équipe des maquettes, mais je vous recommande plutôt de jouer sur l'orientation de la flèche. Exemple : 

**NF05**
-pré-requis-> NF04

**NF04**
<-pré-requis- NF05

2021-05-26 07:57 UTC, benel commented on features/create_bidirectional_link.feature
> +  Quand l’utilisateur clique sur “NF04”
- Évitez de donner des détails sur l"interface (donc évitez "clique").
- Dans le `Quand` reprenez systématiquement le verbe de la fonctionnalité (ici, la création du lien `pre-requis` de `NF05` vers `NF04`).

2021-06-03 09:00 UTC, Xelocks commented
@benel Avec @ThomasRitaine , nous avons modifié les scénarios suite à vos retours. Est-ce que cela convient ?

2021-06-03 09:11 UTC, benel commented
@Xelocks @ThomasRitaine 

> Et la valeur de l’attribut “-pré-requis->” est “NF04”

C'est tout à fait de l'esprit que j'indiquais. 
Après, ça dépend un peu trop des choix d'interface (on pourrait dessiner la flèche de plusieurs manières),  et ça parle de "valeur d'attribut" alors que le lien est une nouvelle primitive.

Je vous suggère une formulation plus abstraite (et qui parle explicitement de "lien"), du genre : 

```cucumber
Et la destination du lien "pré-requis" est "NF04"
```

Du coup, vous voyez ce que serait la formulation de l'étape dans le sens inverse ?

2021-06-09 12:10 UTC, ThomasRitaine commented on features/create_bidirectional_link.feature
> +  Et la destination du lien "antécédent" est "NF04"
Bonjour @benel,
Voici notre modification apportée après [votre dernier commentaire](https://github.com/Hypertopic/Porphyry/pull/507#issuecomment-853717937)
Cette version vous convient-elle ?

2021-06-09 14:42 UTC, benel requested changes
Merci @ThomasRitaine et @Xelocks. Il y a de bonnes choses cependant vous avez beaucoup trop de scénarios. Je vous propose de tout mettre dans un seul.

Comme le verbe d'action de la fonctionnalité est "Créer un lien  bidirectionnel", les scénarios qui ne sont pas de la création doivent disparaître.
Par contre, dans les `Alors` il faudra  vérifier que le lien existe désormais dans les deux sens.

Par, ailleurs, attention : Lu dans l'autre sens : `"NF04" est la destination du lien "pré-requis" de "NF05"` devient `"NF05" est la source du lien "pré-requis" de "NF04"`. 

Autrement dit "pré-requis" et "approndissement" sont spécifique à votre domaine... On ne peut pas les coder "en dur". Du coup, on considère "pré-requis" comme une donnée. Et par contre, ce qui est en dur, c'est "source" et "destination" car ce sont des concepts généralisables à TOUTE relation. Compris ?

2021-06-10 13:05 UTC, Xelocks commented
@benel Voici notre nouvelle version des scénarios. Qu'en pensez-vous ?

2021-06-10 16:00 UTC, benel requested changes
Merci @Xelocks pour cette nouvelle version.

Voici quelques points d'amélioration. Merci d'avance.

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Fonctionnalité : Avoir un lien bidirectionnel entre les items
Merci de corriger le titre de la fonctionnalité en traduisant tout simplement en français celui du ticket.

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Fonctionnalité : Avoir un lien bidirectionnel entre les items
Supprimez l'espace avant `:`. Vous avez raison du point de vue de la syntaxe française, malheureusement c'est incompatible avec la syntaxe de Cucumber.

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Scénario : L’utilisateur souhaite créer un lien bidirectionnel entre deux items
Supprimez l'espace avant `:`. Vous avez raison du point de vue de la syntaxe française, malheureusement c'est incompatible avec la syntaxe de Cucumber.

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Scénario : L’utilisateur souhaite créer un lien bidirectionnel entre deux items
Comme tout est déjà dit dans la fonctionnalité et que vous n'avez qu'un seul cas, vous n'êtes pas obligé de donner un titre au scénario (vous pouvez mettre un titre vide).

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Quand l'utilisateur indique "NF05" comme valeur de l'attribut "pré-requis"
Cette étape semble vouloir dire que `NF05` va devenir le pré-requis de `NF04`, alors que bien entendu c'est l"inverse.  Il faudrait donc inverser `NF04` et `NF05` dans vos deux premières étapes (c'est `NF05` qui est affiché et vous indiquez que son pré-requis est `NF04`).

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Quand l'utilisateur indique "NF05" comme valeur de l'attribut "pré-requis"
`valeur de l'attribut` n'est pas le terme exact. C'est un lien pas un attribut... Le modèle est différent.

Pourquoi ne pas écrire tout simplement : 
```cucumber
Quand l'utilisateur indique "NF04" comme "pré-requis"
```

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Et l’utilisateur clique sur “NF05”
`NF04`

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Alors “NF05” l’item affiché
Idem.

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Et l’utilisateur clique sur “NF05”
On ne peut avoir deux `quand`. C'est une limite assumée de Cucumber.

2021-06-10 16:00 UTC, benel commented on features/create_bidirectional_link.feature
> +Et "NF05" la source du lien “pré-requis” est “NF04”
Pour vérifier les deux, on doit être dans deux pages différentes... Du coup le clic et le changement de page seraient entre les deux...

2021-06-10 16:00 UTC, benel commented on features/portfolio_search.feature
> -Fonctionnalité: Sélectionner des items en cherchant
Attention vous avez supprimé le travail de quelqu'un d'autre !!!

2021-06-16 10:14 UTC, dutoural commented
@benel Voici notre stratégie d'implémentation réalisée avec @maxpid pour cette fonctionnalité. Nous nous sommes d'avantage penchés sur le front-end et avons commencé à réfléchir au back-end. Nous attendons votre premier retour pour finaliser la partie backend.

La stratégie d’implémentation doit répondre aux points suivants : 

1. Il doit être possible de renseigner 2 étiquettes : celle de l’item actuel et celle de l’item de destination 
   (ex : pour NF04 / NF05 → étiquette pré requis pour NF05 et étiquette cours suivant pour NF04)
3. Afficher un InputWithSuggestions pour permettre de renseigner l’item de destination
4. Afficher un bouton valider qui ajoutera l’attribut au clic si tout est bien valide
5. récupérer la liste de tous les items (id et nom) afin de les afficher dans le InputWithSuggestions


Pour répondre à ces différents points, nous avons pensé aux stratégies de développement suivantes : 

Tout d’abord, il faudra recréer un nouveau component React que l’on pourra nommer 
`BidirectionnalLink.jsx
`

Ce composant react sera appelé dans `Item.jsx` au même endroit que les viewpoints
Les étiquettes

On aura tout simplement 2 inputs sans aucunes suggestions avec comme placeholders : 

- renseigner l’étiquette de l’item actuel
- renseigner l’étiquette de l’item de destination

On pourra utiliser le code suivant : 
```
<div class="d-none d-sm-block"><form class="AttributeForm input-group inactive">
    <div class="attributeInput">
        <input id="new-attribute" class="form-control" placeholder="Renseigner l'étiquette de l'item actuel" type="text" value="">
    </div>
</form>
</div>
```

L’input avec les suggestions

Pour implémenter les inputs permettant de choisir les différents items, on pourra réutiliser le composant `InputWithSuggestions` 

```
<div className="d-none d-sm-block">
              <InputWithSuggestions candidates={candidates}
                onSuggestionSelected={this.onSuggestionSelected}
                inputProps={inputProps}
                id={this.props.id}
              />
            </div>
```

Les candidats seront récupérés avec le point 4.

Le bouton valider

On aura un bouton pour valider l’ajout, on pourra utiliser ce code suivant :
`<button type="button" className="btn btn-sm ValidateButton btn" onClick={() => {gestion du backend}`
qui s’occupera de vérifier que tout est OK et d’ajouter l’attribut si c’est bon

Récupérer la liste des items

Afin de permettre d’avoir un input avec des suggestions, on doit récupérer la liste des items pour la renseigner en tant que candidates dans le composant `InputWithSuggestions`. On pourra utiliser le code suivant :

```
  attributesCandidates = memoize(
    (items) => new Items(
      items
    ).getAttributes()
      .map(([key, value]) => key.concat(' : ', value))
      .map(x => ({id: x, name: x, type: 'attribute'}))
  );
```

2021-06-16 17:11 UTC, ThomasRitaine commented
@benel Voici notre nouvelle version des scénarios. Qu'en pensez-vous ?

2021-06-17 08:54 UTC, TheoHoenen commented
```` cucumber 
Soit “NF05” l’item affiché    
Quand l'utilisateur indique "NF04" comme "pré-requis"   
Alors "NF04" est la destination du lien "pré-requis" de "NF05"     
Et "NF05" la source du lien “pré-requis” est “NF04”
```

2021-06-21 15:59 UTC, benel commented
@ThomasRitaine

Merci @TheoHoenen. Je retrouve bien ce que l'on avait fait ensemble jeudi.

> Et "NF05" est la source du lien “pré-requis”“NF04”

Il manque un mot entre "pré-requis" et "NF04"... `vers` ?

Dans le scénario, attention aux guillemets que vous utilisez. Utilisez des guillemets droits.

Enfin, tout ceci pour l'instant est juste en commentaire. N'oubliez pas de modifier votre commit...

2021-06-22 13:09 UTC, Xelocks commented
Merci @TheoHoenen pour l'aide.
@benel Voici donc la nouvelle version du scénario.

2021-06-24 07:33 UTC, benel requested changes
Merci @ThomasRitaine et @Xelocks.

Votre scénario est bon. Il ne manque qu'à tout mettre dans **un seul commit** tout propre, c'est-à-dire : 
- avec uniquement le fichier concerné,
- avec le titre standard (préfixe, nom officiel de la fonctionnalité, lien au ticket),
- avec la mention du co-auteur selon la syntaxe de GitHub.

Ça va aller ?

2021-06-24 07:33 UTC, benel commented on features/portfolio_search.feature
> +Scénario: un attribut puis sa valeur
Attention, vous avez ajouté à votre pull request un scénario qui n'a rien à voir avec le sujet de votre contribution.

2022-04-06 12:56 UTC, closed without merging