FEATURE: Consult items with custom geocoded entities on a map (closes #349)
Hypertopic/Porphyry pull request #509
Opened 2021-05-31 08:00 UTC by Kryddd

## Content

This pull request makes it possible to use a custom geocoding service instead of Google Geocoding API as long as it is compatible.
Some minor changes have been made on the config.yml for this solution to work properly : 
- `interactiveMap ` and `staticMap` attributes for the Google API keys have been replaced by `map.key` (as staticMap is no longer used)
- The geocoding service URI is set by `map.geocodingService`

Therefore, the file should look like that: 

```
user: vitraux
services:
  - http://localhost
map:
  key: google_api_key
  geocodingService: geocoding_service_URI (example: https://maps.googleapis.com/maps/api/geocode/json)

```

By @Kryddd and @franckfotso1 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [X] corresponds to a contribution that should be notified to users,
    - [X] does not generate new errors or warnings at compile or test time,
    - [X] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [X] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [X] be followed by a colon (`:`) with one space after and no space before,
    - [X] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [X] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [X] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [X] related to this very contribution (feature, fix...),
    - [X] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [X] without any typo in variable, class or function names,
    - [X] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2021-05-31 12:34 UTC, benel requested changes
Merci pour cette contribution @Kryddd !

C'est prometteur !!!
Les améliorations à apporter concernent surtout l'historique : 
- bien séparer le refactoring de suppression des cartes statiques et la fonctionnalité de geocoding sur mesure,
- laisser dans un commit à part les modifications de style (mais bon, en même temps, si elles ne font pas partie des règles que l'on a mise pour `eslint`, c'est que ce n'est pas forcément utiles).

2021-05-31 12:34 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> +import { Items } from '../../model.js';
Évitez de mélanger dans les mêmes commits du refactoring (surtout de style) et des fonctionnalités. Ça rend l'intégration (les reverts, le blame, etc.) plus difficile.

2021-05-31 12:34 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> -        src={`https://maps.googleapis.com/maps/api/staticmap?size=640x480&markers=${markers}&key=${this.state.api_key}`}
Vous pourriez peut-être faire un premier commit de refactoring pour supprimer les cartes statiques...

2021-05-31 12:34 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> +    this.state.places.forEach(({ position }) =>
Voir plus haut sur le fait de ne pas mélanger dans un commit des modifications qui n'ont pas de rapport.

2021-05-31 12:34 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> +      console.log(x);
À supprimer quand le code sera finalisé.

2021-05-31 12:34 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> +      .then(places => this.setState({ places }));
Idem sur la séparation entre commits de refactoring et commits de fonctionnalité.

2021-06-02 14:41 UTC, benel commented
Merci et bravo pour cette jolie contribution @krydd et @franckfotso1 !  🎉 🥇 

Par contre vous n'avez pas utilisé la [syntaxe de GitHub qui permet d'associer des co-auteurs à un commit](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). Je vous laisse le corriger où ça vous va comme cela ?

2021-06-02 14:42 UTC, benel submitted a review, later dismissed

2021-06-02 16:29 UTC, Kryddd commented
Merci ! C'est modifié.

2021-06-02 16:31 UTC, benel commented
Il y a mon commit dedans ?!

2021-06-02 16:34 UTC, Kryddd commented
Oui, je l'ai mis pour rester à jour avec la branche principale de Porphyry, je devrais le retirer ?

2021-06-02 17:02 UTC, benel commented
@Kryddd Le problème c'est que ce n'est plus le même commit (il est modifié par Krydd, il y a 35 minutes). 
Si je fais un rebase, j'ai peur qu'il apparaisse deux fois...

2021-06-02 17:11 UTC, Kryddd commented
Oui effectivement, j'ai modifié le commit sans faire attention. Je l'ai supprimé.

2021-06-02 17:24 UTC, merged