Implementation of ticket #272
Hypertopic/Porphyry pull request #510
Opened 2021-05-31 11:12 UTC by Thang-long

## Content

Please describe your contribution here...

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2021-06-02 09:41 UTC, benel requested changes
Merci @Thang-long pour ce scénario et cette implémentation.

L'implémentation est mal du tout (à deux trois petites choses près indiquées en commentaire) ! Le scénario, par contre, nécessitera un travail conséquent par un binôme lors de la prochaine itération.

Merci de soumettre uniquement l'implémentation dans cette demande d'intégration (et donc cette branche).

Si vous avez fait cette implémentation avec une deuxième personne, pensez à utiliser la [syntaxe spécifique à GitHub pour indiquer les co-auteurs dans un commit](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

2021-06-02 09:41 UTC, benel commented on features/portfolio_map.feature
> +
Vos données (ce qui est entre guillemets) n'est pas assez précis ou illustratif.
Il faudra remettre un binôme sur ces scénarios. Ils n'auraient pas dû être considérés comme terminés.

2021-06-02 09:41 UTC, benel commented on features/step_definitions/context.rb
> +end
Inutile dans la phase d'écriture des scénarios de modifier les fichiers "d'étapes".
Ils sont indéfinis, ça suffit pour qu'ils apparaissent "en jaune" plutôt qu'"en rouge" durant les tests.

2021-06-02 09:41 UTC, benel commented on features/step_definitions/outcome.rb
> +end
Idem.

2021-06-02 09:41 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> +	          {this.state.layers && this.state.layers.map(
Pour éviter d'avoir à tester le cas où l'état est nul, arrangez  vous pour que quand il n'y a pas de calques, il y ait un tableau vide.

2021-06-02 09:41 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> +        const portfolio = conf.portfolio;
La création de cette constante n'apporte pas grand chose...

2021-06-02 09:41 UTC, benel commented on src/components/portfolioPage/GeographicMap.jsx
> +          const layers = portfolio[conf.user].layers;
Contrairement à d'autres langages (Java par exemple) où on aime bien utiliser des constantes pour tout ce qui n'est pas modifié, en JavaScript, pour des petites variables qu'on n'utilise que très localement, on en fait plutôt des variables (`let`).

2021-06-02 09:49 UTC, benel commented
Pour l'implémentation, je voulais écrire "pas mal du tout" (ce qui veut dire "très bien") ;)

2021-06-02 09:49 UTC, benel commented
@Thang-long Pour l'implémentation, je voulais écrire "pas mal du tout" (ce qui veut dire "très bien") ;)

2021-06-02 16:14 UTC, Thang-long commented on src/components/portfolioPage/GeographicMap.jsx
> +          const layers = portfolio[conf.user].layers;
Ahhh d'accord, je me suis renseigné un peu plus sur la différence entre `const` et `let`. En fait, j'utilisais uniquement `const` pour "protéger" la modification derrière, sans réel sens. Merci 👍

2021-06-04 15:03 UTC, benel commented
C'est minimaliste comme scénario ;)

On avait parlé plusieurs fois de prendre l'exemple des plans des deux nécropoles du Kerameikos...
L'idée était d'expliquer qu'on les avait dans la configuration et que du coup on les voyait, vous vous souvenez ?

2021-06-04 17:00 UTC, florian-dehe commented
@Thang-long
Je croyais que @ClemUTT et moi-même étions sensé s'occuper du scénario, comme indiqué dans le compte rendu [ici](https://github.com/orgs/Hypertopic/teams/kerameikos/discussions/26) ?

2021-06-04 17:24 UTC, Thang-long commented
> @Thang-long
> Je croyais que @ClemUTT et moi-même étions sensé s'occuper du scénario, comme indiqué dans le compte rendu [ici](https://github.com/orgs/Hypertopic/teams/kerameikos/discussions/26) ?

Je n'ai fait que répondre à la demande de @benel 😀, mais c'est bien vous qui êtes sur le scénario du #272

2021-06-04 17:38 UTC, florian-dehe commented
@Thang-long
Je comprends mieux maintenant merci !

2021-06-07 08:42 UTC, benel commented
Si je comprends bien votre discussion @florian-dehe et @Thang-long, cette demande d'intégration doit être fermée, c'est ça ? C'est important pour moi que je sache ce que je dois relire ou non... Merci d'avance.

2021-06-07 10:56 UTC, Thang-long commented
> Si je comprends bien votre discussion @florian-dehe et @Thang-long, cette demande d'intégration doit être fermée, c'est ça ? C'est important pour moi que je sache ce que je dois relire ou non... Merci d'avance.

Oui, les scénarii ne sont pas encore prêts.

2021-06-07 11:10 UTC, closed without merging