TEST: Scenarios - Add a resource to an item (as a file) (see Hypertopic#142)
Hypertopic/Porphyry pull request #513
Opened 2021-06-02 13:37 UTC by dutoural

## Content

Scenarios (Gherkin) which illustrate the feature "Add a resource to an item (as a file)" (ticket #142) done with
@maxpid . Since the ticket corresponds to a new feature, we put the scenarios in a new file named add_ressource.feature, according to the other scenarios files in the features folder.

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2021-06-02 16:20 UTC, benel requested changes
Merci de cette première version de scénario @dutoural (et votre binôme ?).

Je vous propose que, dans un premier temps, on mette de côté ce que vous avez fait.

Commencez avec un seul scénario (qui illustre le cas le plus courant). On verra plus tard s'il y a d'autres cas à tester.

1. Écrivez le `Quand` en reprenant le nom de la fonctionnalité, et en remplaçant tout ce qui était indéfini par des données précises que vous allez mettre entre guillemets.
2. Demandez vous ensuite comment on va voir que ça a fonctionné : qu'est-ce qui a changé entre avant et après. Cela va vous donner les `Soit` et les `Alors`.

2021-06-02 16:20 UTC, benel commented on features/add_ressource.feature
> +Scénario : Afficher le popup d'ajout des ressources
Vous voyez que `Scénario` n'est pas coloré ?
C'est parce que vous avez mis un espace avant `:`.
On est d'accord que c'est comme cela que l'on fait en français, malheureusement Cucumber ne le sait pas.

2021-06-02 16:20 UTC, benel commented on features/add_ressource.feature
> +Scénario : Afficher le popup d'ajout des ressources
Ne jamais mettre des éléments d'interface (comme "popup") dans les scénarios.
Votre description doit être suffisamment abstraite pour qu'on en ait pas besoin.

2021-06-07 09:10 UTC, benel requested changes
Merci de cette nouvelle version @dutoural et @maxpid !

C'est beaucoup mieux !
Voici quelques conseils supplémentaires pour que ce soit complètement finalisé.

2021-06-07 09:10 UTC, benel commented on features/add_ressource.feature
> +    Soit vitraux le portfolio ouvert
Cette étape n'est pas nécessaire : elle va vous ouvrir la fenêtre principale alors que l'étape suivante va ouvrir directement la page de AXN 009.

2021-06-07 09:10 UTC, benel commented on features/add_ressource.feature
> +Scénario: Annulation de l'ajout
Je n'aurai pas forcément fait ce deuxième scénario... Mais si vous y tenez, pourquoi pas...

Par contre dans les problèmes à anticiper, il y a l'ajout d'une ressource alors qu'on en a déjà une. En effet il ne faut pas que la première disparaisse...

2021-06-07 09:10 UTC, benel commented on features/add_ressource.feature
> +Scénario: Annulation de l'ajout
Une fois que vous avez vos différents cas (scénarios), repassez sur les titres de chacun pour qu'on voie bien la différence entre eux.

2021-06-07 09:10 UTC, benel commented on features/add_ressource.feature
> +    Alors la ressource "vitrail_provenance.pdf" est visible
Le nom est tout à fait acceptable... Ceci dit, si vous voulez quelque chose qui ait plus de sens (pour votre domaine ainsi que pour celui du jeu de test), peut-être que "description" est meilleur (description textuelle du cours, du vitrail et pourquoi pas du dessin, ça marche pour quasiment tous les domaines d'application)...

2021-06-07 09:10 UTC, benel commented on features/add_ressource.feature
> +    Et "AXN 009" l'item affiché
Pour la phase de scénarisation, c'est tout à fait acceptable.
Pour la phase de test par contre, vos collègues devront probablement changer cette étape, car sinon ils auront du mal à lancer le test plusieurs fois de suite.

2021-06-07 09:10 UTC, benel commented on features/add_ressource.feature
> +    Quand l'utilisateur annule l'ajout de la ressource "vitrail_provenance.pdf"
Sur la formulation du `Quand`, il faudrait être plus clair sur le fait qu'il commence l'ajout de la ressource et l'annule.

2021-06-07 09:18 UTC, maxpid commented on features/add_ressource.feature
> +    Quand l'utilisateur annule l'ajout de la ressource "vitrail_provenance.pdf"
on pourrait rajouter :
```suggestion
    Et "vitrail_provenance.pdf" est affiché 
```
Qu'en pensez vous ?

2021-06-07 09:26 UTC, benel commented on features/add_ressource.feature
> +    Quand l'utilisateur annule l'ajout de la ressource "vitrail_provenance.pdf"
@maxpid 

Je pense qu'il vaut mieux faire les deux dans **la même** étape.

En effet le "Quand" correspond toujours au cœur de la fonctionnalité (ici : "ajout d'une ressource") et du cas ("qui est annulé avant d'être achevé").

2021-06-07 09:26 UTC, maxpid commented on features/add_ressource.feature
> +Scénario: Annulation de l'ajout
Pour ce scénario on imagine le fait qu'un utilisateur pourrait faire une erreur en ajoutant une mauvaise ressources. Cela lui laisserait la possibilité de revenir en arrière. Pour ceux qui est du problème soulever j'imagine que chaque "bouton" d'annulation pourrait être lié à une seul ressource pour éviter ce genre de problème.

2021-06-07 09:31 UTC, maxpid commented on features/add_ressource.feature
> +    Quand l'utilisateur annule l'ajout de la ressource "vitrail_provenance.pdf"
```suggestion
    Quand l'utilisateur ajoute ressource "vitrail_provenance.pdf" et l'annule 
```
Je ne suis pas sur de moi, cela me dérange de mettre un "et" dans le "quand". Je ne sait pas si l'on a le droit de le faire.

2021-06-07 09:53 UTC, benel commented on features/add_ressource.feature
> +    Quand l'utilisateur annule l'ajout de la ressource "vitrail_provenance.pdf"
> Je ne suis pas sur de moi, cela me dérange de mettre un "et" dans le "quand". Je ne sait pas si l'on a le droit de le faire.

Cucumber n'interprète que les premiers mots. Donc vous avez tout à, fait le droit.
Par contre la formulation n'est pas très claire ("l'annule" ? annule quoi ?)...

2021-06-08 12:24 UTC, dutoural commented
@benel 
J'ai modifié le test suite à vos remarques en espérant que cette fois ci, ce soit la bonne !

2021-06-09 05:00 UTC, benel commented
@dutoural Merci. On y est presque...

- Je vous avais plutôt suggéré "description" comme nom du PDF (comme je le disais, ça marche pour tous les domaines d'application). Ça donnerait par exemple `AXN_009_description.pdf`.
- "est cachée" est un peu maladroit, car quand quelque chose est caché c'est que cette chose existe quand même (essayez quelque chose du genre : `Alors il n'y a pas de ressource "AXN_009_description.pdf" visible`).
- N'oubliez pas rassembler toute votre contribution dans un seul commit intitulé `SCENARIO: Add a resource to an item as a file (see #42).`
- Si le travail résulte du travail d'un binôme, le commit doit indiquer pour votre collègue `Co-authored-by: Nom Complet <adresse électronique référencée dans GitHub>`

2021-06-10 06:36 UTC, benel commented
@dutoural 

Merci de cette contribution. Comme on vient d'en discuter autour du tableau, il va falloir remettre l'historique d'aplomb.

Si vous n'y arrivez pas, vous pouvez soit vous faire aider par un étudiant qui veut son badge d'assistance Git, soit par moi.

2021-06-11 09:06 UTC, closed without merging