FEATURE: Authorize a contributor to edit a viewpoint (see #183)
Hypertopic/Porphyry pull request #515
Opened 2021-06-04 09:43 UTC by JacquesMironneau

## Content

Implementation of issue #183, made with @Anas9820.

- Viewpoints with a list of contributors can be edited only by them (but existing viewpoints, without a list or with an empty list, are still writable by any authenticated user).
- On creation, a viewpoint has its author as its only contributor.
- Any contributor of a viewpoint can authorize another user to contribute.

2021-06-04 13:13 UTC, benel requested changes
Merci beaucoup pour ces contributions !!! @JacquesMironneau @Anas9820 

À part deux petits détails, il faudrait surtout séparer en commits différents les contributions qui n'ont pas de rapport entre elles.

Une fois ces petites modifcations effectuées, votre fonctionnalité et vos fix viendront rejoindre la branche principale !

2021-06-04 13:13 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +    conf.then(x => {
Je n'ai pas compris pourquoi vous n'utilisez pas `SETTINGS` (qui justement attend que `conf`).
Vous prenez au goût aux `then` ;)

Le mélange de style de programmation est ici voulu. On garde les `then` pour les vraies requêtes mais sans alourdir avec l'obtention du fichier de configuration (qui en plus est très rapide).

2021-06-04 13:13 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +    console.log(this.state.topics);
Attention, vous avez oublié votre message de debug...

2021-06-04 13:13 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +    }
Ce morceau a l'air de correspondre à une autre contribution. Un fix peut-être ?
Merci de le mettre dans un commit à part (dans la même branche si vous voulez). 
Ça permet de rendre le `blame` plus pertinent. Ça permet de mieux cibler un éventuel `revert`.
Et puis ça permettra de documenter votre fix dans l'historique de Git (qui fait office de "changelog").

2021-06-04 13:13 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +    let style = this.state.title ? 'col-md-8 p-4' : 'col-md-12 p-4';
Il y avait un petit problème de mise en page quand il n'y a pas de titre ?

Merci d'en faire un commit à part (avec son utilisation plus bas, anciennement ligne 37.

2021-06-04 13:13 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +        topic.new = true;
Pourquoi intervertir les deux lignes ? Ça posait un problème ?

2021-06-04 13:38 UTC, JacquesMironneau commented on src/components/viewpointPage/Outliner.jsx
> +    }
C'est bien une contribution de notre commit, en effet cela permet d'éviter un léger effet de bord qui ajoute ce qui s'apparentent à 2 item vide sur l'affichage des items

2021-06-04 13:39 UTC, JacquesMironneau commented on src/components/viewpointPage/Outliner.jsx
> +    }
Très bien je vais l'ajouter en temps que fix

2021-06-04 13:40 UTC, JacquesMironneau commented on src/components/viewpointPage/Outliner.jsx
> +        topic.new = true;
Cela doit plutôt être une erreur d'inattention, je vais le corriger

2021-06-04 14:03 UTC, JacquesMironneau commented on src/components/viewpointPage/Outliner.jsx
> +    }
Selon vous, le plus simple est d'enlever cette contribution, faire un commit, puis la rerajouter dans un commit suivant ?

2021-06-04 14:06 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +    }
Je vous encourage à utiliser un préparateur visuel de commit ligne à ligne. Vous en avez un dans Atom par exemple. Ainsi, parmi ce qui est dans votre espace de travail, vous choisissez les lignes qui sont à mettre dans le prochain commit et celles que vous gardez pour après.

2021-06-04 14:07 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +    }
Vous voyez ce que je veux dire ?

2021-06-04 14:08 UTC, benel commented on src/components/viewpointPage/Outliner.jsx
> +    }
Et effectivement, oui, comme vous avez déjà un commit, vous pouvez l'amender puis ajouter le reste avec d'autres commits ensuite.

2021-06-04 14:16 UTC, JacquesMironneau commented on src/components/viewpointPage/Outliner.jsx
> +    let style = this.state.title ? 'col-md-8 p-4' : 'col-md-12 p-4';
Le test d'absence de titre permet de vérifier si le viewpoint est créer ou en création (page ou l'on rentre le nom de ce dernier). Ce style permet d'avoir la création en plein écran et l'affichage partagé lors de la modification du viewpoint. (avec sur la gauche les contributeur et à droite le viewpoint)

2021-06-04 14:33 UTC, JacquesMironneau commented
J'ai fait les modifications que vous m'aviez demander:
Ajout de la feature (sans fix)
Puis ajout du premier fix (discussion ici: https://github.com/Hypertopic/Porphyry/pull/515#discussion_r645557125 )

Après avoir revérifier le comportement de la feature, il s'avère que le refactor que nous avions fait règle le second fix, le code n'était donc plus utile je l'ai donc supprimé. (discussion: https://github.com/Hypertopic/Porphyry/pull/515#discussion_r645555424  )

2021-06-04 14:46 UTC, JacquesMironneau commented on src/components/viewpointPage/Outliner.jsx
> +    }
D'accord je comprends merci !

2021-06-04 15:39 UTC, benel commented
Merci @JacquesMironneau. Comme ça, en deux commits, c'est très propre ! 

@JacquesMironneau @Anas9820 Je suis en train de tester votre code. Ça fonctionne très bien ! Bravo !

Par contre, quand je le récupère par Git, l'auteur est un certain "PashmiDev", c'est normal ?
Par ailleurs, vous n'avez pas utilisé la syntaxe qui permet dans GitHub de déclarer un co-auteur dans un commit (`Co-authored-by:`), c'est normal ?

2021-06-04 15:52 UTC, JacquesMironneau commented
@benel 
C'était l'ancien pseudonyme associé à mon compte github !
> Par ailleurs, vous n'avez pas utilisé la syntaxe qui permet dans GitHub de déclarer un co-auteur dans un commit (Co-authored-by:), c'est normal ?

Je n'ai pas pensé à cette fonctionnalité, voulez-vous que je fasse la modification

2021-06-04 16:02 UTC, benel commented
> C'était l'ancien pseudonyme associé à mon compte github !

Si vous le souhaitez, vous pouvez changer la configuration de Git sur votre ordinateur (soit globalement, soit pour un dossier donné). À vous de voir...

> Je n'ai pas pensé à cette fonctionnalité, voulez-vous que je fasse la modification ?

Ben c'est surtout pour votre collègue... 

Pour l'instant, ça ne vous prendra que deux minutes à modifier (surtout si vous le faites à coup avec cherry-pick et amend). Alors que plus ça ira et plus ça deviendra difficile à modifier (Git c'est une chaîne de Merkle comme la Blockchain).

2021-06-04 16:04 UTC, Anas9820 commented
Il est vrai que je mérite une certaine reconnaissance également :D

2021-06-04 16:04 UTC, benel commented
Ah ?

2021-06-04 16:13 UTC, JacquesMironneau commented
@benel 
Comment dois-je utiliser le cherry-pick ?
Je pensais simplement checkout puis amend les commit un par un.

2021-06-04 16:53 UTC, JacquesMironneau commented
@benel 
Après quelques erreurs avec le cherry-pick les modifications sont faites (auteur et co-auteur)

2021-06-04 17:06 UTC, JacquesMironneau commented
>Pour l'instant, ça ne vous prendra que deux minutes à modifier (surtout si vous le faites à coup de cherry-pick et d'amend)

J'ai pu tester également le `git rebase -i HEAD~2`, il permet de facilement faire une modification de message de commit (en utilisant les fonctions disponibles: dans notre cas le reword).

2021-06-07 09:20 UTC, merged

2021-06-07 09:20 UTC, JacquesMironneau commented
@benel est-ce que ces changements vous conviennent ?

2021-06-07 09:27 UTC, benel commented
@JacquesMironneau Les grands esprits se rencontrent ;)
J'ai intégré votre contribution juste avant que vous ne posiez la question. :)

2021-06-07 09:28 UTC, benel commented
Je fais les derniers tests avant de vous féliciter officiellement ;)