TEST: Scenarios - Subscribe to a corpus (see Hypertopic#501)
Hypertopic/Porphyry pull request #517
Opened 2021-06-04 15:52 UTC by cedricleandres

## Content

Scenarios which illustrate the feature "Subscribe to a corpus" (ticket #501) done with @sarah-ngn .
Since the ticket corresponds to a new feature, we put the scenarios in a new file named subscribe_corpus.feature, according to the other scenarios files in the features folder.
---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2021-06-07 09:48 UTC, benel requested changes
Merci @cedricleandres pour ce scénario.

Comme je le disais précédemment, il aura sans doute à être un peu retravaillé au moment de l'écriture des tests, mais pour l'instant il peut être validé en tant que scénario.

À propos de l'historique : 
- merci d'utiliser le préfixe `SCENARIO:`,
- si vous l'avez co-écrit en binôme, pensez à utiliser la syntaxe (`Co-authored-by: name <name@example.com>`) qui permettra à GitHub d'associer également votre collègue au commit,
-  le nom donné à la fonctionnalité est plus clair que le nom originel, ça vaudrait le coup de le mettre aussi dans le _commit_ (`Get notified on corpus changes`).

Merci d'avance.

2021-06-07 09:48 UTC, benel commented on features/subscribe_corpus.feature
> +Scénario:  suite à un ajout d'item
Attention, vous avez mis un espace de trop.

2021-06-07 13:47 UTC, cedricleandres commented on features/subscribe_corpus.feature
> +Scénario:  suite à un ajout d'item
Merci @benel pour le retour. De ce fait dois-je relancer un nouveau commit en vue d'enlever l'espace de trop?
Et pour son intitulé "SCENARIO: Get notified on corpus changes (see #501) Co-authored-by: @sarah-ngn <sarah.nguyen@utt.fr>" ?

2021-06-07 13:54 UTC, benel commented
@cedricleandres 

> De ce fait dois-je relancer un nouveau commit en vue d'enlever l'espace de trop ?

Vous devez "l'amender" (pas seulement pour l'espace, je ne suis pas si sadique) mais surtout pour le message de commit (formatage du titre, et mention de la co-autrice dans les lignes qui suivent).

> Co-authored-by: @sarah-ngn sarah.nguyen@utt.fr" ?

Le premier paramètre est le nom complet.
Le second (qui doit être entre chevrons) est l'adresse électronique déclarée dans GitHub.

2021-06-08 13:53 UTC, cedricleandres commented on features/subscribe_corpus.feature
> +Scénario:  suite à un ajout d'item
J'ai essayé d'amender le commit, mais une fois les modifications faites en local, je souhaite exporter cela dans ma branche distante et j'obtiens l'erreur lié aux conflits avec la branche locale. Dois je forcer le push avec par exmple: "git push -f origin master"

Ci dessous l'erreur:
![image](https://user-images.githubusercontent.com/65378394/121197568-b3e63400-c871-11eb-8647-43a6619b45de.png)

@benel

2021-06-08 14:08 UTC, benel commented
Oui c’est ça : il faut forcer le push. 

Aurélien Bénel

> Le 8 juin 2021 à 15:54, Cedric Leandres TAMGNO TAMOUFE ***@***.***> a écrit :
> 
> ﻿
> @cedricleandres commented on this pull request.
> 
> In features/subscribe_corpus.feature:
> 
> > @@ -0,0 +1,16 @@
> +#language: fr
> +
> +Fonctionnalité:  Etre informé des nouveautés relatives à un corpus
> +
> +Scénario: suite à une modification d'item
> +
> +Soit "Graines d'artistes" un corpus auquel l'utilisateur est abonné
> +Lorsque l'item "1997_MS_06_FRA_R_A"  est modifié
> +Alors l'utilisateur est informé de la modification de  l'item "1997_MS_06_FRA_R_A"  par une notification dans son client RSS
> +
> +Scénario:  suite à un ajout d'item
> J'ai essayé d'amender le commit, mais une fois les modifications faites en local, je souhaite exporter cela dans ma branche distante et j'obtiens l'erreur lié aux conflits avec la branche locale. Dois je forcer le push avec par exmple: "git push -f origin master"?
> 
> Ci dessous l'erreur:
> 
> 
> @benel
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-09 05:05 UTC, benel commented
@cedricleandres @sarah-ngn 

C'est presque bon... Mais le co-authored doit être sur la troisième ligne du commit : 
```
SCENARIO: Get notified on corpus changes (see #501). 

Co-authored-by: Sarah NGUYEN <sarah.nguyen@utt.fr>
```
Sinon ça ne fonctionne pas...

2022-04-06 13:03 UTC, closed without merging