FIX: The picture of a shared item is not visible on a Facebook publication #380
Hypertopic/Porphyry pull request #520
Opened 2021-06-09 12:58 UTC by LSauter68140

## Content

Now with FB sharing button from disqus we can share a stained glass's Photo with a thumbnail on FB
---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    -    [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

Co-authored-by: Toine-prog <62764276+Toine-prog@users.noreply.github.com>
Co-authored-by: YaellePihan <yaelle.pihan@gmail.com>

2021-06-09 15:01 UTC, benel requested changes
Merci @LSauter68140 pour cette contribution.

Je valide votre code source. 🏅 

Par contre, merci de corriger l'historique de manière à ce qu'il ne reste qu'un seul _commit_  et qu'il soit de la forme suivante : 
- sa première ligne de texte (titre) doit reprendre le titre du ticket : `FIX: The picture of a shared item is not visible on a Facebook publication (see #380).` ;
- sa troisième ligne de texte doit mentionner vos co-auteurs s'il y en a (notamment si vous l'avez fait en binôme), selon la syntaxe spéciale de GitHub : `Co-authored-by: Nom Complet <adresse électronique connue de GitHub>`.

Merci d'avance.

2021-06-09 21:51 UTC, LSauter68140 commented
euh je crois que j'ai fait un truc de travers, j"ai rajouté des anciens commits sans faire exprès en voulant juste modifier le nom de 1 commit, c'est possible de les supprimer ?
Et pour le ``Co-authored-by: `` j'arrive pas à le faire fonctionner j'ai rajouter les noms et les adresses e-mails mais....

2021-06-10 04:12 UTC, benel commented
> pour le Co-authored-by: j'arrive pas à le faire fonctionner j'ai rajouter les noms et les adresses e-mails mais....

C'est parce qu'il faut mettre l'adresse électronique entre "chevrons" (`<>`).

Par ailleurs, même si ce n'est pas une obligation, je vous recommande de mettre le nom complet plutôt que le login. C'est préférable pour la reconnaissance de votre droit d'auteur (droit moral uniquement puisque c'est en open-source).

> euh je crois que j'ai fait un truc de travers, j"ai rajouté des anciens commits sans faire exprès en voulant juste modifier le nom de 1 commit

Effectivement, c'est bizarre... Je pense que vous avez fait votre _rebase_ à l'envers (de A sur B, au lieu de B sur A), si ça peut vous consoler, ça m'est déjà arrivé.
Et en plus vous étiez sur la branche principale.
Voici comment faire pour régler les deux problèmes : 

1. Mettez votre fichier modifié (celui qui contient votre contribution) de côté (sur le bureau où n'importe où).

2. Faites un `git reset --hard` sur un commit plus ancien que le plus ancien de ceux qui s'affichent ici.

3. Mettez à jour votre branche principale avec un `git pull` sur l'entrepôt officiel (Hypertopic/Porphyry).

4. Changez de branche.

5. Ajoutez votre fichier que vous aviez mis de côté.

6. Créez un nouveau commit tout propre.

7. Publiez votre branche thématique et faites une nouvelle pull request dessus (oui, cette PR-ci malheureusement est associée à v7).

8. Passez sur la branche principale et publiez la de manière forcée afin de rétablir sa cohérence avec la branche principale de l'entrepôt officiel.

Ça va aller ?

2021-06-10 07:37 UTC, LSauter68140 commented
j'ai pu refaire correctement une pull request avec tous les conseils que vous m'avez donnés, donc on peut fermer celle ci ?

2021-06-10 07:50 UTC, benel commented
> j'ai pu refaire correctement une pull request avec tous les conseils que vous m'avez donnés

Super ! 

> donc on peut fermer celle ci ?

OK.

2021-06-10 07:51 UTC, closed without merging