SCENARIO: Register as a contributor (see #184 )
Hypertopic/Porphyry pull request #526
Opened 2021-06-11 07:42 UTC by Samnoel95

## Content

@benel 

Voici la pull request pour les scénarios  du ticket #184. 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2021-06-15 14:40 UTC, benel requested changes
Merci pour cette contribution @Samnoel95.

Vos scénarios sont très bien (même si probablement ils devront être retouchés un peu par ceux qui feront les tests).

Quelques petites pistes d'amélioration : 
- j'ai noté dans le code des micro-détails qui permettraient de rendre l'affichage des tests plus concis.
- pour le nom du fichier, si vous pouvez le rendre plus cohérent avec les autres du même dossier (de la forme "objet_action") ce serait mieux. Par exemple : `user_register.feature`.

Pour l'historique, merci : 
- [ ] de tout mettre dans un seul commit,
- [ ] de mentionner le co-auteur s'il y en a un (en mettant à la troisième ligne du commit `Co-authored-by: Prenom Nom <name@example.com>`.

Merci d'avance.

2021-06-15 14:40 UTC, benel commented on features/register_as_contributor.feature
> +Scénario: L’utilisateur souhaite s’inscrire avec un e-mail au format valide
Comme les titres de scénarios sont affichés par Cucumber immédiatement après et dessous le titre de la fonctionnalité, vous pouvez le simplifier en `avec un e-mail au format valide`.

2021-06-15 14:40 UTC, benel commented on features/register_as_contributor.feature
> +Scénario: L’utilisateur souhaite s’inscrire avec un e-mail au format non valide
Comme les titres de scénarios sont affichés par Cucumber immédiatement après et dessous le titre de la fonctionnalité, vous pouvez le simplifier en `avec un e-mail au format non valide`.

2021-06-20 20:02 UTC, Samnoel95 commented
@benel 
Les modifications ont été effectuées.

2021-06-22 05:24 UTC, benel approved these changes
🎉

2021-06-22 05:25 UTC, merged