FEATURE: Register as a contributor (see #184 )
Hypertopic/Porphyry pull request #528
Opened 2021-06-12 15:15 UTC by theobour

Implementation of ticket #184  with @cedfre .

- Creation of page named Subscribe and accessible with the following endpoint : /subscribe
- Add of a button "S'inscire..." into the header which redirect to /subscribe

@benel we are still needing some help about the creation. In fact, in subscribe/subscribePage our function handleConnection successfully create a user but then we don't know how to create the session for the user so he appears as connected.

2021-06-15 16:41 UTC, benel commented
@theobour @cedfre 

> we don't know how to create the session for the user 

A session is created by sending a `POST` on `/_session`.

You can check how it is done on log in: https://github.com/Hypertopic/Porphyry/blob/d1438c5e1a3198f5d8aec8218bc38c4d6da241d9/src/components/Authenticated.jsx#L75-L81

> so he appears as connected.

The user should see the state change in `Authenticated` when he is redirected to the original page... So there should be nothing to do special in order to make visible the session opening.

2021-06-15 17:13 UTC, theobour commented
I commited some changes.
Now, after user creation, I create his session and redirect him to /

As all my commits are a bit "dirty" I will redo all the commit history if you validate this feature

@benel

2021-06-16 16:37 UTC, benel requested changes
Merci @theobour pour cette contribution.

Ça a l'air pas mal. Je n'ai pas encore testé mais j'ai déjà quelques remarques que j'ai mises directement dans des commentaires ligne à ligne.
La plus importante concerne des mises à jour de l'affichage (déclenchées par `setState`) qui ne me semblent pas nécessaires.

Par ailleurs, j'ai vu que vous aviez ajouté des phrases d'interface mais je n'ai pas vu leur localisation (en français et anglais). Vous allez pouvoir : 
1. ajouter les clefs avec `npm run extract` (https://github.com/Hypertopic/Porphyry/blob/v7/package.json#L36),
2. mettre à jour les valeurs dans `src/locales/en/messages.po` et `src/locales/fr/messages.po`.

2021-06-16 16:37 UTC, benel commented on src/components/Authenticated.jsx
> +        <a href="#login" onClick={this.handleAsk}><Trans>Se connecter...</Trans></a><br />
Petite astuce de git : comme les "blame" sont ligne à ligne, mettez plutôt votre `br` a la ligne suivante, ainsi vous éviterez de prendre la paternité de la ligne "Se connecter".

2021-06-16 16:37 UTC, benel commented on src/components/Authenticated.jsx
> +        <Link to={'/subscribe'}>
Je n'ai pas souvent vu "subscribe" pour s'inscrire sur un site anglophone. C'est plutôt utilisé pour s'abonner à un flux, à une chaîne...

Twitter, Instagram et GitHub utilisent l'expression "Sign up". Facebook utilise "Create new account" au début mais "Sign up" ensuite. Ça semble être le plus courant....

Sinon vous pouvez aussi utiliser "Register" comme dans le titre de la fonctionnalité (et comme sur eBay ou EpicGames par exemple).

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +      password: '',
Je ne suis pas certain que ce soit une bonne idée de tout mettre dans l'état comme cela... En particulier, vous allez déclencher avec setState des réaffichages qui n'ont pas trop de raisons d'être.

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +      password: '',
Limitez vous aux données dont la modification justement doit déclencher un `render`. Et s'il n'y en a aucun, ce n'est pas grave...

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +    console.log(conf);
N'oubliez pas d'enlever vos messages de debug.

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +      options = options || {};
Vous pouvez intégrer le "ou" dans la ligne suivante.

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +      return fetch(x.services[0] + ':5984/_users', options);
Attention, ce numéro de port est spécifique à votre configuration et ne fonctionnera pas ailleurs. 
Normalement le chemin `/_users` est disponible aussi sur le proxy (donc sur le port 80 pour vous).

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +        if (!x.ok) throw new Error('Bad credentials!');
Vous êtes sûr que c'est la seule explication possible de l'erreur ?

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +      .catch(() => this.setState({user: ''}));
Voir ma remarque au début sur le fait que je pense qu'il vaut mieux que `user` ne soit pas un état.

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +      this.setState({user});
Voir ma remarque au début sur le fait que je pense qu'il vaut mieux que `user` ne soit pas un état.

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +    }
Voir ma remarque au début sur le fait que je pense qu'il vaut mieux que `user` ne soit pas un état.

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +                      placeholder="Bob" name="pseudo" onChange={(e) => this.handleChange(e)}/>
>  placeholder="Bob" 

Ce n'est pas courant d'avoir un pseudo avec une majuscule... Par ailleurs, on encourage plutôt les noms de famille...

2021-06-16 16:37 UTC, benel commented on src/components/subscribePage/Subscribe.jsx
> +                    <input type="email" className="form-control" id="email" placeholder="bob@bob.fr" name="email"
> placeholder="bob@bob.fr"

Ce n'est pas courant d'avoir un nom de domaine à son prénom...

2021-06-16 18:25 UTC, theobour commented on src/components/Authenticated.jsx
> +        <Link to={'/subscribe'}>
C'est vrai que le subscribe serait plutôt dans le cadre d'un abonnement.
J'ai changé subscribe par "register" sur l'ensemble de mes changements. Le chemin d'accès, le nom du fichier .jsx, du dossier...

2021-06-16 18:26 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +      password: '',
J'ai effectivement enlevé ces éléments de l'état du composant pour ne pas déclencher de nombreux render

2021-06-16 18:26 UTC, theobour commented on src/components/Authenticated.jsx
> +        <a href="#login" onClick={this.handleAsk}><Trans>Se connecter...</Trans></a><br />
J'ai mis le ```<br />``` à la ligne suivante pour ne plus avoir de problèmes.

2021-06-16 18:27 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +    console.log(conf);
Je viens d'enlever ce ```console.log()```inutile

2021-06-16 18:28 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +      options = options || {};
J'ai mis le options directement après dans l'appel de la fonction

2021-06-16 18:28 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +      .catch(() => this.setState({user: ''}));
J'ai retiré le user de l'état car il était effectivement inutile.
Dans le ```catch``` j'ai remplacé par un ```console.error()```

2021-06-16 18:29 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +      this.setState({user});
J'ai retiré le user de l'état car il était effectivement inutile.
Dans le ```catch``` j'ai remplacé par un ```console.error()```

2021-06-16 18:29 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +    }
J'ai retiré le user de l'état car il était effectivement inutile.
Dans le ```catch``` j'ai remplacé par un ```console.error()```

2021-06-16 18:29 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +                      placeholder="Bob" name="pseudo" onChange={(e) => this.handleChange(e)}/>
J'ai mis un placeholder plus cohérent avec un pseudo

2021-06-16 18:29 UTC, theobour commented on src/components/subscribePage/Subscribe.jsx
> +                    <input type="email" className="form-control" id="email" placeholder="bob@bob.fr" name="email"
J'ai mis un placeholder plus cohérent avec un email

2021-06-16 18:30 UTC, theobour commented
@benel avant de refaire mon historique des commits pour une soumission finale j'ai encore des soucis avec ```npm run extract```

Voici le problème :
```
> porphyry_v7@0.1.0 extract
> lingui extract

/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/@lingui/cli/api/compat.js:56
        throw e;
        ^

ReferenceError: [BABEL] src/TopicTree.js: Unknown option: /Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-preset-react-app/index.js")
    at Logger.error (/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at /Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/theobour/Documents/UTT/P21/IF05/Porphyry/node_modules/babel-core/lib/transformation/file/index.js:212:65)
```

2021-06-17 09:30 UTC, theobour commented
@benel je viens de corriger toutes vos remarques et j'ai ajouté les traductions dans les messages.po

Désormais tout est bon sauf mon historique des commits qui est un peu long et peu organisé. @JacquesMironneau il me semble que tu l'as fait il y a une ou deux semaine, peux-tu m'aider là dessus ?

2021-06-17 12:52 UTC, Anas9820 commented
@theobour  @cedfre 

Hello, avec @JacquesMironneau  on a remarqué un petit problème au niveau de l'email. En effet, quand on entre un email au mauvais format (comme bobacme.org), l'inscription passe tout de même et il est alors possible de se connecter avec cet email erroné. Peut être que le type "email" dans l'input n'est pas pris en compte?

2021-06-17 12:55 UTC, JacquesMironneau commented
Avec @Anas9820 on a regarder un plus en détail, et il serait par exemple possible d'ajouter une verification avec une regexp.

```html
<input type="email" value={ this.state.email } onChange={ handleOnChange } />
```
```js

let handleOnChange = ( email ) => {
   let regexp = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

    if ( regexp.test(email) ) {
     // Le mail est valide
    }
}
```

Qu'en pensez-vous ? @cedfre @theobour

2021-06-17 13:00 UTC, JacquesMironneau commented
@theobour 
Pour la gestion de ton historique, tu devrais essayer de faire un:
git reset --soft HEAD~14 // Le nombre dépend de ton nombre de commit, mais l'idée est de retourner au commit v7

Ensuite tu add simplement uniquement ce que tu as besoin avec un 
git add ./fichier
Tu peux aussi enlever les éventuels fichiers en trop (le .idea...)
avec git reset ./fichier

Puis tu peux faire le commit en faisant
git commit

Et tu peux ajouter les Co-author en écrivant le texte ci dessous en dessous du message de commit

Co-authored-by: PseudoGithub <MailGithub>

2021-06-17 13:17 UTC, JacquesMironneau commented
D'ailleurs @theobour @cedfre dans les langues nous avons vu 2 petites fautes
Pour l'anglais:
Pseudonyme (au lieu de pseudonym)
Et pour le français, vous avez mis "S'inscire" au lieu de "S'inscrire..."

2021-06-17 13:49 UTC, benel commented
@JacquesMironneau @Anas9820 

> let handleOnChange = ( email )

Dans la stratégie d'implémentation, on n'avait pas plutôt parlé d'une vérification par le navigateur (grâce à une expression régulière que l"on peut mettre dans les attributs de l'élément HTML) ?

2021-06-17 13:53 UTC, JacquesMironneau commented
@benel 
Nous avions évoquer plusieurs possibilitées durant la dernière réunion, au début nous pensions à l'attribut type='email ' dans l'html, mais ce n'a pas l'air de réellement fonctionner

2021-06-17 13:55 UTC, JacquesMironneau commented
Sinon, oui il serait possible d'utiliser l'attribut [pattern`](https://www.w3schools.com/TAGS/att_input_pattern.asp) avec la regexp proposée ci-dessus.

2021-06-17 14:08 UTC, benel commented
> Nous avions évoquer plusieurs possibilitées durant la dernière réunion, au début nous pensions à l'attribut type='email ' dans l'html, mais ce n'a pas l'air de réellement fonctionner

Je viens de regarder sur MDN. Comme souvent la documentation en français est inutilisable. 😢 

Par contre vous trouverez votre bonheur dans la version anglaise : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/email#pattern_validation

2021-06-17 14:35 UTC, theobour commented
Merci @Anas9820 et @JacquesMironneau pour votre aide !
Du fait que nous utilisons une fonction ```handleConnection()``` pour exécuter l'action d'envoyer le formulaire, la vérification du ```type="email"``` ne fait pas effet. 
J'ai donc repris votre solution d'utiliser une expression régulière tout en gardant l'expression régulière du ```type=email``` décrite dans la documentation fournit pas @benel .

Maintenant que tout est fini, je vais passer à la réorganisation des commits

2021-06-17 15:12 UTC, theobour commented
Merci @JacquesMironneau de m'avoir aidé en vocal pour débloquer la situation sur git.

2021-06-22 04:12 UTC, benel commented
Merci @theobour pour cette contribution.

> Du fait que nous utilisons une fonction handleConnection() pour exécuter l'action d'envoyer le formulaire, la vérification du type="email" ne fait pas effet.
J'ai donc repris votre solution d'utiliser une expression régulière tout en gardant l'expression régulière du type=email décrite dans la documentation fournit par @benel .

Je n'ai pas compris votre message... Vous avez mis la vérification HTML5 pour me faire plaisir alors qu'elle ne peut pas fonctionner, c'est ça ?

2021-06-22 04:17 UTC, benel commented
> Je n'ai pas compris votre message... Vous avez mis la vérification HTML5 pour me faire plaisir alors qu'elle ne peut pas fonctionner, c'est ça ?

Ou alors, vous voulez dire que vous avez déplacé vers React l'expression régulière initialement faite pour HTML5 , c'est ça ?

2021-06-22 08:17 UTC, theobour commented
> > Je n'ai pas compris votre message... Vous avez mis la vérification HTML5 pour me faire plaisir alors qu'elle ne peut pas fonctionner, c'est ça ?
> 
> Ou alors, vous voulez dire que vous avez déplacé vers React l'expression régulière initialement faite pour HTML5 , c'est ça ?

C'est cette option. J'ai déplacé l'expression régulière dans le React, car dans le HTML5 elle n'était pas prise en compte.

Il me semble que maintenant tout est bon pour le merge :)

2021-06-25 19:07 UTC, theobour commented
Bonjour @benel ,

Faut-il encore faire d'autres changement pour valider cette pull request ?

Bonne journée,

2021-06-27 13:43 UTC, benel commented on src/components/registerPage/Register.jsx
> +      return fetch(x.services[0] + ':5984/_users', options || {});
Pour information, il ne fallait pas mettre le port 5984 (celui-ci est inaccessible en production). C'était bien sur le service principal (tel qu'indiqué dans la  configuration).

2021-06-27 14:01 UTC, benel commented on src/components/registerPage/Register.jsx
> +      return fetch(x.services[0] + '/_users', options || {});
Pour information, il manquait un slash final à l'URI pour passer le proxy.
Je précise que c'est uniquement pour information : inutile de le modifier : je suis déjà en train d'éditer votre commit.

2021-06-27 14:36 UTC, benel commented
Intégré en tant que 16dd83420f71345b2b9a08cfce564eb4ddff9abf 🎉

2021-06-27 14:36 UTC, closed without merging