TEST: Register as a contributor #184
Hypertopic/Porphyry pull request #535
Opened 2021-06-17 15:31 UTC by JacquesMironneau

Realization of the #184 tests with @Samnoel95 and @Anas9820 

Note for the part : "	Et l'utilisateur est redirigé vers la page d'édition de l'item "SNZ 006" "
In the test implementation, it is very similar to "le titre de l'item affiché est {string}"", however in order to keep the sense of the scenario  we have decided to keep the  "	Et l'utilisateur est redirigé vers la page d'édition de l'item "SNZ 006" despite of its implementation.

2021-06-22 08:20 UTC, benel requested changes
Merci pour cette contribution @JacquesMironneau @Samnoel95 et @Anas9820 !
Je ne peux pas encore le tester, mais ça a l'air très bien.


Vous serait-il possible de ne garder que les tests dans votre commit ?
En effet, le scénario a déjà été intégré.

Quant à amender la contribution, vous serait-il possible de mettre la référence au ticket entre parenthèses et précédé de `see`, autrement dit : `TEST: Register as a contributor (see #184).`.

Merci d'avance !

2021-06-22 08:40 UTC, JacquesMironneau commented
@benel 
J'ai fait les modifications

2021-06-25 13:53 UTC, benel commented
@JacquesMironneau @Samnoel95 @Anas9820

Vos tests sont plutôt bien mais ils ont des effets de bord : on ne peut pas les lancer plusieurs fois de suite.
Vous voyez pourquoi ?

Vous voyez comment éviter ça ?

2021-06-25 14:49 UTC, JacquesMironneau commented
@benel 

Oui, quand un utilisateur s'enregistre son compte n'est pas supprimer par la suite, on ne pourra donc pas recréer un utilisateur ayant le même email.

Je vois deux solutions possibles :
- générer un mail pseudo aléatoire
- supprimer le compte après le scénario

2021-06-25 14:51 UTC, benel commented
> Je vois deux solutions possibles :
- générer un mail pseudo aléatoire
- supprimer le compte après le scénario

La première solution me semble préférable (cela veut dire bien-sûr retirer les paramètres des étapes correspondantes).

2021-06-25 16:53 UTC, JacquesMironneau commented
@benel 
J'ai générer un compte aléatoire en ajoutant un hash devant le mail et le pseudo, de cette manière il est toujours possible de passer un mail valide ou non (celui-ci sera simplement plus long: A721727A72AZUJAHIJZAYbob@acme.org et AJZ1828UY8ZEBKbobacme.org par exemple).
Cela-vous convient-il ?

2021-06-27 14:35 UTC, benel commented
Intégré en tant que dd879e43746c6a1b0ee5acbbc4253e9e181cfd55 🎉

2021-06-27 14:35 UTC, closed without merging