The building map should remain active when a topic is selected (see #591)
Hypertopic/Porphyry pull request #599
Opened 2022-05-13 08:07 UTC by Couapy

## Content

Please describe your contribution here...

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2022-05-13 08:19 UTC, Couapy commented
Tests fails, please see #560 status.

2022-05-13 09:37 UTC, benel approved these changes

2022-05-13 16:26 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> -      && selectionJSON.data.length === 1
I will add this line again since its deletion make browsing fail (reproduction scenario: select a topic and then unselect it).

2022-05-13 16:33 UTC, benel requested changes
Sorry but your implementation for #591 breaks a feature ("[Remove a criterium from the query](https://github.com/Hypertopic/Porphyry/commit/f6aed5c7325fde4f7e038da20f5ab26563c775a7)").

2022-05-13 16:33 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> -      && selectionJSON.data.length === 1
Hmm. But deleting this line seems necessary for your feature... So I suppose your feature needs a little more work...

2022-05-13 17:56 UTC, benel commented
I have added a [scenario](https://github.com/Hypertopic/Porphyry/commit/f6aed5c7325fde4f7e038da20f5ab26563c775a7)  to help you identify the regression.

2022-05-13 18:23 UTC, benel commented
Sorry, the scenario did not correspond to the exact case of the regression. Here is a new version of the scenario: https://github.com/Hypertopic/Porphyry/blob/v7/features/portfolio_browse.feature#L27-L36

2022-05-14 08:26 UTC, benel commented
Please note that fix-560 is now merged (then you shouldn't include it in this PR anymore).

2022-05-14 12:45 UTC, benel commented on src/components/portfolioPage/Portfolio.jsx
> -      && selectionJSON.data.length === 1
Maybe `>0 `?

2022-05-20 13:47 UTC, benel approved these changes

2022-05-20 14:28 UTC, benel requested changes
I've tried to integrate your code in v7 but it seems incompatible with 2be6c217b8c1e94e599410f48f8693ef2210d4c3.

It breaks the test "features/portfolio_browse_spatially.feature:16".

I tried to double check both contributions and tweak your code to pass the test, but I cannot find where the incompatibility stands. An author of one of both contributions may find it more quickly...

2022-05-20 14:51 UTC, benel commented
I suspect that the problem is that you are getting the map from selected items (instead of corpora), while it is not there anymore once you have selected the topic.
Did you check the scenario manually? 
I wonder if the test is not a false positive...

2022-06-03 09:30 UTC, merged