FIX : Layout should be more mobile friendly on item page #603
Hypertopic/Porphyry pull request #605
Opened 2022-05-20 10:00 UTC by Couapy

Co-authored-by: Maël Marchand <mael.marchand@utt.fr>
Co-authored-by: Thomond5 <Thomond5@users.noreply.github.com>
Co-authored-by: LucasJeanpierre <lulu.jeanpierre@gmail.com>
Co-authored-by: IrisBR <IrisBR@users.noreply.github.com>

## Content

Make mobile usage friendly. Please see #603

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2022-05-20 13:39 UTC, benel requested changes
Thank you very much for this contribution that will be useful VERY soon...

A small question however: What happened to the CSS, did you really change every line of code? Or maybe you had a problem with CRLF settings in git? Could you please fix that?

2022-05-21 16:03 UTC, Couapy commented
I fixed it, is it ok?

2022-05-22 07:42 UTC, benel commented on src/components/itemPage/Item.jsx
> +          setAttribute={this._setAttribute} deleteAttribute={this._deleteAttribute} />
Il est déconseillé d'inclure dans un commit une ligne qui n'a pas de rapport avec le sujet du commit.
Dans ce cas précis, cela a créé un conflit de modification qui aurait pu être évité.

2022-05-22 15:48 UTC, benel approved these changes

2022-05-22 17:17 UTC, merged