TEST : for feature "Get similar items ac. to an item's topic" (see#40)
Hypertopic/Porphyry pull request #78
Opened 2018-04-15 12:44 UTC by gumn

## Content

TEST for feature "Get similar items ac. to an item's topic" (see#40)

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

2018-04-19 07:43 UTC, benel requested changes
Petits problèmes dans le titre :

- en anglais, il n'y a pas d'espace avant les deux points,
- inutile de préciser "for feature", un test porte forcément sur une fonctionnalité,
- pour que le lien vers la fonctionnalité soit actif, il faut un espace avant le dièse.

2018-04-19 08:15 UTC, benel approved these changes

2018-06-12 16:25 UTC, benel commented
Pull request approved (after a few edits). Now integrated to branch v7. Well done!

2018-06-12 16:25 UTC, closed without merging

2018-06-12 19:59 UTC, gumn commented
Super ! J'ai vu qu'à un moment ça ne passait pas avec Travis, mais je n'ai pas compris pourquoi et ce que vous avez fait pour que ça passe !